// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: egress/egress.proto

package egress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// S3Upload S3 兼容存储上传配置
type S3Upload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Upload) Reset() {
	*x = S3Upload{}
	mi := &file_egress_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Upload) ProtoMessage() {}

func (x *S3Upload) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Upload.ProtoReflect.Descriptor instead.
func (*S3Upload) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{0}
}

func (x *S3Upload) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3Upload) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *S3Upload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Upload) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Upload) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// AliOSSUpload 阿里 OSS 上传配置
type AliOSSUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliOSSUpload) Reset() {
	*x = AliOSSUpload{}
	mi := &file_egress_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliOSSUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliOSSUpload) ProtoMessage() {}

func (x *AliOSSUpload) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliOSSUpload.ProtoReflect.Descriptor instead.
func (*AliOSSUpload) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{1}
}

func (x *AliOSSUpload) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AliOSSUpload) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AliOSSUpload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AliOSSUpload) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AliOSSUpload) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// FileOutput 文件输出配置
type FileOutput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FileType string                 `protobuf:"bytes,1,opt,name=fileType,proto3" json:"fileType"` // mp4, ogg, webm
	Filepath string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath"` // 输出文件路径模板，支持 {room_name}/{time} 等变量
	// Types that are valid to be assigned to Output:
	//
	//	*FileOutput_S3
	//	*FileOutput_AliOss
	Output        isFileOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOutput) Reset() {
	*x = FileOutput{}
	mi := &file_egress_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOutput) ProtoMessage() {}

func (x *FileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOutput.ProtoReflect.Descriptor instead.
func (*FileOutput) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{2}
}

func (x *FileOutput) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileOutput) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileOutput) GetOutput() isFileOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *FileOutput) GetS3() *S3Upload {
	if x != nil {
		if x, ok := x.Output.(*FileOutput_S3); ok {
			return x.S3
		}
	}
	return nil
}

func (x *FileOutput) GetAliOss() *AliOSSUpload {
	if x != nil {
		if x, ok := x.Output.(*FileOutput_AliOss); ok {
			return x.AliOss
		}
	}
	return nil
}

type isFileOutput_Output interface {
	isFileOutput_Output()
}

type FileOutput_S3 struct {
	S3 *S3Upload `protobuf:"bytes,3,opt,name=s3,proto3,oneof"`
}

type FileOutput_AliOss struct {
	AliOss *AliOSSUpload `protobuf:"bytes,4,opt,name=aliOss,proto3,oneof"`
}

func (*FileOutput_S3) isFileOutput_Output() {}

func (*FileOutput_AliOss) isFileOutput_Output() {}

// SegmentOutput HLS 分段输出配置
type SegmentOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilenamePrefix  string                 `protobuf:"bytes,1,opt,name=filenamePrefix,proto3" json:"filenamePrefix"`
	PlaylistName    string                 `protobuf:"bytes,2,opt,name=playlistName,proto3" json:"playlistName"`
	SegmentDuration int32                  `protobuf:"varint,3,opt,name=segmentDuration,proto3" json:"segmentDuration"` // 分段时长(秒)，默认 6
	// Types that are valid to be assigned to Output:
	//
	//	*SegmentOutput_S3
	//	*SegmentOutput_AliOss
	Output        isSegmentOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentOutput) Reset() {
	*x = SegmentOutput{}
	mi := &file_egress_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentOutput) ProtoMessage() {}

func (x *SegmentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentOutput.ProtoReflect.Descriptor instead.
func (*SegmentOutput) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentOutput) GetFilenamePrefix() string {
	if x != nil {
		return x.FilenamePrefix
	}
	return ""
}

func (x *SegmentOutput) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *SegmentOutput) GetSegmentDuration() int32 {
	if x != nil {
		return x.SegmentDuration
	}
	return 0
}

func (x *SegmentOutput) GetOutput() isSegmentOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *SegmentOutput) GetS3() *S3Upload {
	if x != nil {
		if x, ok := x.Output.(*SegmentOutput_S3); ok {
			return x.S3
		}
	}
	return nil
}

func (x *SegmentOutput) GetAliOss() *AliOSSUpload {
	if x != nil {
		if x, ok := x.Output.(*SegmentOutput_AliOss); ok {
			return x.AliOss
		}
	}
	return nil
}

type isSegmentOutput_Output interface {
	isSegmentOutput_Output()
}

type SegmentOutput_S3 struct {
	S3 *S3Upload `protobuf:"bytes,4,opt,name=s3,proto3,oneof"`
}

type SegmentOutput_AliOss struct {
	AliOss *AliOSSUpload `protobuf:"bytes,5,opt,name=aliOss,proto3,oneof"`
}

func (*SegmentOutput_S3) isSegmentOutput_Output() {}

func (*SegmentOutput_AliOss) isSegmentOutput_Output() {}

// StreamOutput 推流输出配置
type StreamOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol"` // rtmp, srt
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutput) Reset() {
	*x = StreamOutput{}
	mi := &file_egress_egress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutput) ProtoMessage() {}

func (x *StreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutput.ProtoReflect.Descriptor instead.
func (*StreamOutput) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{4}
}

func (x *StreamOutput) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StreamOutput) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// RecordingInfo 录制任务信息
type RecordingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressID      string                 `protobuf:"bytes,1,opt,name=egressID,proto3" json:"egressID"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName"`
	MeetingID     string                 `protobuf:"bytes,3,opt,name=meetingID,proto3" json:"meetingID"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status"` // EGRESS_STARTING, EGRESS_ACTIVE, EGRESS_ENDING, EGRESS_COMPLETE, EGRESS_FAILED
	StartedAt     int64                  `protobuf:"varint,5,opt,name=startedAt,proto3" json:"startedAt"`
	EndedAt       int64                  `protobuf:"varint,6,opt,name=endedAt,proto3" json:"endedAt"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error"`
	RoomID        string                 `protobuf:"bytes,9,opt,name=roomID,proto3" json:"roomID"`
	FileResult    *FileResult            `protobuf:"bytes,10,opt,name=fileResult,proto3" json:"fileResult"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingInfo) Reset() {
	*x = RecordingInfo{}
	mi := &file_egress_egress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingInfo) ProtoMessage() {}

func (x *RecordingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingInfo.ProtoReflect.Descriptor instead.
func (*RecordingInfo) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{5}
}

func (x *RecordingInfo) GetEgressID() string {
	if x != nil {
		return x.EgressID
	}
	return ""
}

func (x *RecordingInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RecordingInfo) GetMeetingID() string {
	if x != nil {
		return x.MeetingID
	}
	return ""
}

func (x *RecordingInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordingInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RecordingInfo) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *RecordingInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RecordingInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RecordingInfo) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *RecordingInfo) GetFileResult() *FileResult {
	if x != nil {
		return x.FileResult
	}
	return nil
}

// FileResult 录制文件结果
type FileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename"`
	StartedAt     int64                  `protobuf:"varint,2,opt,name=startedAt,proto3" json:"startedAt"`
	EndedAt       int64                  `protobuf:"varint,3,opt,name=endedAt,proto3" json:"endedAt"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration"` // 时长(纳秒)
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size"`         // 文件大小(字节)
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location"`  // 存储位置/下载地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResult) Reset() {
	*x = FileResult{}
	mi := &file_egress_egress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResult) ProtoMessage() {}

func (x *FileResult) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResult.ProtoReflect.Descriptor instead.
func (*FileResult) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{6}
}

func (x *FileResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileResult) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *FileResult) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *FileResult) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *FileResult) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileResult) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// StartRoomRecordingReq 开始房间合成录制（整个房间画面）
type StartRoomRecordingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName"`
	MeetingID     string                 `protobuf:"bytes,2,opt,name=meetingID,proto3" json:"meetingID"`         // 关联的会议ID（可选）
	Layout        string                 `protobuf:"bytes,3,opt,name=layout,proto3" json:"layout"`               // 布局: speaker, grid, single-speaker（默认 speaker）
	FileOutput    *FileOutput            `protobuf:"bytes,4,opt,name=fileOutput,proto3" json:"fileOutput"`       // 文件输出（与 segmentOutput/streamOutput 互斥）
	SegmentOutput *SegmentOutput         `protobuf:"bytes,5,opt,name=segmentOutput,proto3" json:"segmentOutput"` // HLS 分段输出
	StreamOutput  *StreamOutput          `protobuf:"bytes,6,opt,name=streamOutput,proto3" json:"streamOutput"`   // 推流输出
	AudioOnly     bool                   `protobuf:"varint,7,opt,name=audioOnly,proto3" json:"audioOnly"`        // 仅录制音频
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoomRecordingReq) Reset() {
	*x = StartRoomRecordingReq{}
	mi := &file_egress_egress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoomRecordingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoomRecordingReq) ProtoMessage() {}

func (x *StartRoomRecordingReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoomRecordingReq.ProtoReflect.Descriptor instead.
func (*StartRoomRecordingReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{7}
}

func (x *StartRoomRecordingReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *StartRoomRecordingReq) GetMeetingID() string {
	if x != nil {
		return x.MeetingID
	}
	return ""
}

func (x *StartRoomRecordingReq) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *StartRoomRecordingReq) GetFileOutput() *FileOutput {
	if x != nil {
		return x.FileOutput
	}
	return nil
}

func (x *StartRoomRecordingReq) GetSegmentOutput() *SegmentOutput {
	if x != nil {
		return x.SegmentOutput
	}
	return nil
}

func (x *StartRoomRecordingReq) GetStreamOutput() *StreamOutput {
	if x != nil {
		return x.StreamOutput
	}
	return nil
}

func (x *StartRoomRecordingReq) GetAudioOnly() bool {
	if x != nil {
		return x.AudioOnly
	}
	return false
}

type StartRoomRecordingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RecordingInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoomRecordingResp) Reset() {
	*x = StartRoomRecordingResp{}
	mi := &file_egress_egress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoomRecordingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoomRecordingResp) ProtoMessage() {}

func (x *StartRoomRecordingResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoomRecordingResp.ProtoReflect.Descriptor instead.
func (*StartRoomRecordingResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{8}
}

func (x *StartRoomRecordingResp) GetInfo() *RecordingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// StartTrackRecordingReq 开始轨道合成录制（音视频通话录制）
type StartTrackRecordingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName"`
	MeetingID     string                 `protobuf:"bytes,2,opt,name=meetingID,proto3" json:"meetingID"`
	AudioTrackID  string                 `protobuf:"bytes,3,opt,name=audioTrackID,proto3" json:"audioTrackID"`
	VideoTrackID  string                 `protobuf:"bytes,4,opt,name=videoTrackID,proto3" json:"videoTrackID"`
	FileOutput    *FileOutput            `protobuf:"bytes,5,opt,name=fileOutput,proto3" json:"fileOutput"`
	SegmentOutput *SegmentOutput         `protobuf:"bytes,6,opt,name=segmentOutput,proto3" json:"segmentOutput"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrackRecordingReq) Reset() {
	*x = StartTrackRecordingReq{}
	mi := &file_egress_egress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrackRecordingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrackRecordingReq) ProtoMessage() {}

func (x *StartTrackRecordingReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrackRecordingReq.ProtoReflect.Descriptor instead.
func (*StartTrackRecordingReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{9}
}

func (x *StartTrackRecordingReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *StartTrackRecordingReq) GetMeetingID() string {
	if x != nil {
		return x.MeetingID
	}
	return ""
}

func (x *StartTrackRecordingReq) GetAudioTrackID() string {
	if x != nil {
		return x.AudioTrackID
	}
	return ""
}

func (x *StartTrackRecordingReq) GetVideoTrackID() string {
	if x != nil {
		return x.VideoTrackID
	}
	return ""
}

func (x *StartTrackRecordingReq) GetFileOutput() *FileOutput {
	if x != nil {
		return x.FileOutput
	}
	return nil
}

func (x *StartTrackRecordingReq) GetSegmentOutput() *SegmentOutput {
	if x != nil {
		return x.SegmentOutput
	}
	return nil
}

type StartTrackRecordingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RecordingInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrackRecordingResp) Reset() {
	*x = StartTrackRecordingResp{}
	mi := &file_egress_egress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrackRecordingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrackRecordingResp) ProtoMessage() {}

func (x *StartTrackRecordingResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrackRecordingResp.ProtoReflect.Descriptor instead.
func (*StartTrackRecordingResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{10}
}

func (x *StartTrackRecordingResp) GetInfo() *RecordingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// StopRecordingReq 停止录制
type StopRecordingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressID      string                 `protobuf:"bytes,1,opt,name=egressID,proto3" json:"egressID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingReq) Reset() {
	*x = StopRecordingReq{}
	mi := &file_egress_egress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingReq) ProtoMessage() {}

func (x *StopRecordingReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingReq.ProtoReflect.Descriptor instead.
func (*StopRecordingReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{11}
}

func (x *StopRecordingReq) GetEgressID() string {
	if x != nil {
		return x.EgressID
	}
	return ""
}

type StopRecordingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RecordingInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingResp) Reset() {
	*x = StopRecordingResp{}
	mi := &file_egress_egress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingResp) ProtoMessage() {}

func (x *StopRecordingResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingResp.ProtoReflect.Descriptor instead.
func (*StopRecordingResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{12}
}

func (x *StopRecordingResp) GetInfo() *RecordingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ListRecordingsReq 查询录制列表
type ListRecordingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName"`      // 按房间名过滤（可选）
	MeetingID     string                 `protobuf:"bytes,2,opt,name=meetingID,proto3" json:"meetingID"`    // 按会议ID过滤（可选）
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=activeOnly,proto3" json:"activeOnly"` // 仅返回进行中的录制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordingsReq) Reset() {
	*x = ListRecordingsReq{}
	mi := &file_egress_egress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordingsReq) ProtoMessage() {}

func (x *ListRecordingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordingsReq.ProtoReflect.Descriptor instead.
func (*ListRecordingsReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{13}
}

func (x *ListRecordingsReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ListRecordingsReq) GetMeetingID() string {
	if x != nil {
		return x.MeetingID
	}
	return ""
}

func (x *ListRecordingsReq) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListRecordingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecordingInfo       `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordingsResp) Reset() {
	*x = ListRecordingsResp{}
	mi := &file_egress_egress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordingsResp) ProtoMessage() {}

func (x *ListRecordingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordingsResp.ProtoReflect.Descriptor instead.
func (*ListRecordingsResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{14}
}

func (x *ListRecordingsResp) GetItems() []*RecordingInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// UpdateLayoutReq 更新录制布局
type UpdateLayoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressID      string                 `protobuf:"bytes,1,opt,name=egressID,proto3" json:"egressID"`
	Layout        string                 `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLayoutReq) Reset() {
	*x = UpdateLayoutReq{}
	mi := &file_egress_egress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLayoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLayoutReq) ProtoMessage() {}

func (x *UpdateLayoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLayoutReq.ProtoReflect.Descriptor instead.
func (*UpdateLayoutReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateLayoutReq) GetEgressID() string {
	if x != nil {
		return x.EgressID
	}
	return ""
}

func (x *UpdateLayoutReq) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

type UpdateLayoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RecordingInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLayoutResp) Reset() {
	*x = UpdateLayoutResp{}
	mi := &file_egress_egress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLayoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLayoutResp) ProtoMessage() {}

func (x *UpdateLayoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLayoutResp.ProtoReflect.Descriptor instead.
func (*UpdateLayoutResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateLayoutResp) GetInfo() *RecordingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// UpdateStreamReq 更新推流地址
type UpdateStreamReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EgressID         string                 `protobuf:"bytes,1,opt,name=egressID,proto3" json:"egressID"`
	AddOutputUrls    []string               `protobuf:"bytes,2,rep,name=addOutputUrls,proto3" json:"addOutputUrls"`
	RemoveOutputUrls []string               `protobuf:"bytes,3,rep,name=removeOutputUrls,proto3" json:"removeOutputUrls"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStreamReq) Reset() {
	*x = UpdateStreamReq{}
	mi := &file_egress_egress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamReq) ProtoMessage() {}

func (x *UpdateStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamReq.ProtoReflect.Descriptor instead.
func (*UpdateStreamReq) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStreamReq) GetEgressID() string {
	if x != nil {
		return x.EgressID
	}
	return ""
}

func (x *UpdateStreamReq) GetAddOutputUrls() []string {
	if x != nil {
		return x.AddOutputUrls
	}
	return nil
}

func (x *UpdateStreamReq) GetRemoveOutputUrls() []string {
	if x != nil {
		return x.RemoveOutputUrls
	}
	return nil
}

type UpdateStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RecordingInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamResp) Reset() {
	*x = UpdateStreamResp{}
	mi := &file_egress_egress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamResp) ProtoMessage() {}

func (x *UpdateStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_egress_egress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamResp.ProtoReflect.Descriptor instead.
func (*UpdateStreamResp) Descriptor() ([]byte, []int) {
	return file_egress_egress_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStreamResp) GetInfo() *RecordingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_egress_egress_proto protoreflect.FileDescriptor

const file_egress_egress_proto_rawDesc = "" +
	"\n" +
	"\x13egress/egress.proto\x12\ropenim.egress\"\x8c\x01\n" +
	"\bS3Upload\x12\x1c\n" +
	"\taccessKey\x18\x01 \x01(\tR\taccessKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\x90\x01\n" +
	"\fAliOSSUpload\x12\x1c\n" +
	"\taccessKey\x18\x01 \x01(\tR\taccessKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\xb0\x01\n" +
	"\n" +
	"FileOutput\x12\x1a\n" +
	"\bfileType\x18\x01 \x01(\tR\bfileType\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12)\n" +
	"\x02s3\x18\x03 \x01(\v2\x17.openim.egress.S3UploadH\x00R\x02s3\x125\n" +
	"\x06aliOss\x18\x04 \x01(\v2\x1b.openim.egress.AliOSSUploadH\x00R\x06aliOssB\b\n" +
	"\x06output\"\xf1\x01\n" +
	"\rSegmentOutput\x12&\n" +
	"\x0efilenamePrefix\x18\x01 \x01(\tR\x0efilenamePrefix\x12\"\n" +
	"\fplaylistName\x18\x02 \x01(\tR\fplaylistName\x12(\n" +
	"\x0fsegmentDuration\x18\x03 \x01(\x05R\x0fsegmentDuration\x12)\n" +
	"\x02s3\x18\x04 \x01(\v2\x17.openim.egress.S3UploadH\x00R\x02s3\x125\n" +
	"\x06aliOss\x18\x05 \x01(\v2\x1b.openim.egress.AliOSSUploadH\x00R\x06aliOssB\b\n" +
	"\x06output\">\n" +
	"\fStreamOutput\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\"\xbc\x02\n" +
	"\rRecordingInfo\x12\x1a\n" +
	"\begressID\x18\x01 \x01(\tR\begressID\x12\x1a\n" +
	"\broomName\x18\x02 \x01(\tR\broomName\x12\x1c\n" +
	"\tmeetingID\x18\x03 \x01(\tR\tmeetingID\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartedAt\x18\x05 \x01(\x03R\tstartedAt\x12\x18\n" +
	"\aendedAt\x18\x06 \x01(\x03R\aendedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\x03R\tupdatedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06roomID\x18\t \x01(\tR\x06roomID\x129\n" +
	"\n" +
	"fileResult\x18\n" +
	" \x01(\v2\x19.openim.egress.FileResultR\n" +
	"fileResult\"\xac\x01\n" +
	"\n" +
	"FileResult\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tstartedAt\x18\x02 \x01(\x03R\tstartedAt\x12\x18\n" +
	"\aendedAt\x18\x03 \x01(\x03R\aendedAt\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\xc7\x02\n" +
	"\x15StartRoomRecordingReq\x12\x1a\n" +
	"\broomName\x18\x01 \x01(\tR\broomName\x12\x1c\n" +
	"\tmeetingID\x18\x02 \x01(\tR\tmeetingID\x12\x16\n" +
	"\x06layout\x18\x03 \x01(\tR\x06layout\x129\n" +
	"\n" +
	"fileOutput\x18\x04 \x01(\v2\x19.openim.egress.FileOutputR\n" +
	"fileOutput\x12B\n" +
	"\rsegmentOutput\x18\x05 \x01(\v2\x1c.openim.egress.SegmentOutputR\rsegmentOutput\x12?\n" +
	"\fstreamOutput\x18\x06 \x01(\v2\x1b.openim.egress.StreamOutputR\fstreamOutput\x12\x1c\n" +
	"\taudioOnly\x18\a \x01(\bR\taudioOnly\"J\n" +
	"\x16StartRoomRecordingResp\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.openim.egress.RecordingInfoR\x04info\"\x99\x02\n" +
	"\x16StartTrackRecordingReq\x12\x1a\n" +
	"\broomName\x18\x01 \x01(\tR\broomName\x12\x1c\n" +
	"\tmeetingID\x18\x02 \x01(\tR\tmeetingID\x12\"\n" +
	"\faudioTrackID\x18\x03 \x01(\tR\faudioTrackID\x12\"\n" +
	"\fvideoTrackID\x18\x04 \x01(\tR\fvideoTrackID\x129\n" +
	"\n" +
	"fileOutput\x18\x05 \x01(\v2\x19.openim.egress.FileOutputR\n" +
	"fileOutput\x12B\n" +
	"\rsegmentOutput\x18\x06 \x01(\v2\x1c.openim.egress.SegmentOutputR\rsegmentOutput\"K\n" +
	"\x17StartTrackRecordingResp\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.openim.egress.RecordingInfoR\x04info\".\n" +
	"\x10StopRecordingReq\x12\x1a\n" +
	"\begressID\x18\x01 \x01(\tR\begressID\"E\n" +
	"\x11StopRecordingResp\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.openim.egress.RecordingInfoR\x04info\"m\n" +
	"\x11ListRecordingsReq\x12\x1a\n" +
	"\broomName\x18\x01 \x01(\tR\broomName\x12\x1c\n" +
	"\tmeetingID\x18\x02 \x01(\tR\tmeetingID\x12\x1e\n" +
	"\n" +
	"activeOnly\x18\x03 \x01(\bR\n" +
	"activeOnly\"H\n" +
	"\x12ListRecordingsResp\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.openim.egress.RecordingInfoR\x05items\"E\n" +
	"\x0fUpdateLayoutReq\x12\x1a\n" +
	"\begressID\x18\x01 \x01(\tR\begressID\x12\x16\n" +
	"\x06layout\x18\x02 \x01(\tR\x06layout\"D\n" +
	"\x10UpdateLayoutResp\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.openim.egress.RecordingInfoR\x04info\"\x7f\n" +
	"\x0fUpdateStreamReq\x12\x1a\n" +
	"\begressID\x18\x01 \x01(\tR\begressID\x12$\n" +
	"\raddOutputUrls\x18\x02 \x03(\tR\raddOutputUrls\x12*\n" +
	"\x10removeOutputUrls\x18\x03 \x03(\tR\x10removeOutputUrls\"D\n" +
	"\x10UpdateStreamResp\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.openim.egress.RecordingInfoR\x04info2\xa5\x04\n" +
	"\rEgressService\x12a\n" +
	"\x12StartRoomRecording\x12$.openim.egress.StartRoomRecordingReq\x1a%.openim.egress.StartRoomRecordingResp\x12d\n" +
	"\x13StartTrackRecording\x12%.openim.egress.StartTrackRecordingReq\x1a&.openim.egress.StartTrackRecordingResp\x12R\n" +
	"\rStopRecording\x12\x1f.openim.egress.StopRecordingReq\x1a .openim.egress.StopRecordingResp\x12U\n" +
	"\x0eListRecordings\x12 .openim.egress.ListRecordingsReq\x1a!.openim.egress.ListRecordingsResp\x12O\n" +
	"\fUpdateLayout\x12\x1e.openim.egress.UpdateLayoutReq\x1a\x1f.openim.egress.UpdateLayoutResp\x12O\n" +
	"\fUpdateStream\x12\x1e.openim.egress.UpdateStreamReq\x1a\x1f.openim.egress.UpdateStreamRespB&Z$github.com/openimsdk/protocol/egressb\x06proto3"

var (
	file_egress_egress_proto_rawDescOnce sync.Once
	file_egress_egress_proto_rawDescData []byte
)

func file_egress_egress_proto_rawDescGZIP() []byte {
	file_egress_egress_proto_rawDescOnce.Do(func() {
		file_egress_egress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egress_egress_proto_rawDesc), len(file_egress_egress_proto_rawDesc)))
	})
	return file_egress_egress_proto_rawDescData
}

var file_egress_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_egress_egress_proto_goTypes = []any{
	(*S3Upload)(nil),                // 0: openim.egress.S3Upload
	(*AliOSSUpload)(nil),            // 1: openim.egress.AliOSSUpload
	(*FileOutput)(nil),              // 2: openim.egress.FileOutput
	(*SegmentOutput)(nil),           // 3: openim.egress.SegmentOutput
	(*StreamOutput)(nil),            // 4: openim.egress.StreamOutput
	(*RecordingInfo)(nil),           // 5: openim.egress.RecordingInfo
	(*FileResult)(nil),              // 6: openim.egress.FileResult
	(*StartRoomRecordingReq)(nil),   // 7: openim.egress.StartRoomRecordingReq
	(*StartRoomRecordingResp)(nil),  // 8: openim.egress.StartRoomRecordingResp
	(*StartTrackRecordingReq)(nil),  // 9: openim.egress.StartTrackRecordingReq
	(*StartTrackRecordingResp)(nil), // 10: openim.egress.StartTrackRecordingResp
	(*StopRecordingReq)(nil),        // 11: openim.egress.StopRecordingReq
	(*StopRecordingResp)(nil),       // 12: openim.egress.StopRecordingResp
	(*ListRecordingsReq)(nil),       // 13: openim.egress.ListRecordingsReq
	(*ListRecordingsResp)(nil),      // 14: openim.egress.ListRecordingsResp
	(*UpdateLayoutReq)(nil),         // 15: openim.egress.UpdateLayoutReq
	(*UpdateLayoutResp)(nil),        // 16: openim.egress.UpdateLayoutResp
	(*UpdateStreamReq)(nil),         // 17: openim.egress.UpdateStreamReq
	(*UpdateStreamResp)(nil),        // 18: openim.egress.UpdateStreamResp
}
var file_egress_egress_proto_depIdxs = []int32{
	0,  // 0: openim.egress.FileOutput.s3:type_name -> openim.egress.S3Upload
	1,  // 1: openim.egress.FileOutput.aliOss:type_name -> openim.egress.AliOSSUpload
	0,  // 2: openim.egress.SegmentOutput.s3:type_name -> openim.egress.S3Upload
	1,  // 3: openim.egress.SegmentOutput.aliOss:type_name -> openim.egress.AliOSSUpload
	6,  // 4: openim.egress.RecordingInfo.fileResult:type_name -> openim.egress.FileResult
	2,  // 5: openim.egress.StartRoomRecordingReq.fileOutput:type_name -> openim.egress.FileOutput
	3,  // 6: openim.egress.StartRoomRecordingReq.segmentOutput:type_name -> openim.egress.SegmentOutput
	4,  // 7: openim.egress.StartRoomRecordingReq.streamOutput:type_name -> openim.egress.StreamOutput
	5,  // 8: openim.egress.StartRoomRecordingResp.info:type_name -> openim.egress.RecordingInfo
	2,  // 9: openim.egress.StartTrackRecordingReq.fileOutput:type_name -> openim.egress.FileOutput
	3,  // 10: openim.egress.StartTrackRecordingReq.segmentOutput:type_name -> openim.egress.SegmentOutput
	5,  // 11: openim.egress.StartTrackRecordingResp.info:type_name -> openim.egress.RecordingInfo
	5,  // 12: openim.egress.StopRecordingResp.info:type_name -> openim.egress.RecordingInfo
	5,  // 13: openim.egress.ListRecordingsResp.items:type_name -> openim.egress.RecordingInfo
	5,  // 14: openim.egress.UpdateLayoutResp.info:type_name -> openim.egress.RecordingInfo
	5,  // 15: openim.egress.UpdateStreamResp.info:type_name -> openim.egress.RecordingInfo
	7,  // 16: openim.egress.EgressService.StartRoomRecording:input_type -> openim.egress.StartRoomRecordingReq
	9,  // 17: openim.egress.EgressService.StartTrackRecording:input_type -> openim.egress.StartTrackRecordingReq
	11, // 18: openim.egress.EgressService.StopRecording:input_type -> openim.egress.StopRecordingReq
	13, // 19: openim.egress.EgressService.ListRecordings:input_type -> openim.egress.ListRecordingsReq
	15, // 20: openim.egress.EgressService.UpdateLayout:input_type -> openim.egress.UpdateLayoutReq
	17, // 21: openim.egress.EgressService.UpdateStream:input_type -> openim.egress.UpdateStreamReq
	8,  // 22: openim.egress.EgressService.StartRoomRecording:output_type -> openim.egress.StartRoomRecordingResp
	10, // 23: openim.egress.EgressService.StartTrackRecording:output_type -> openim.egress.StartTrackRecordingResp
	12, // 24: openim.egress.EgressService.StopRecording:output_type -> openim.egress.StopRecordingResp
	14, // 25: openim.egress.EgressService.ListRecordings:output_type -> openim.egress.ListRecordingsResp
	16, // 26: openim.egress.EgressService.UpdateLayout:output_type -> openim.egress.UpdateLayoutResp
	18, // 27: openim.egress.EgressService.UpdateStream:output_type -> openim.egress.UpdateStreamResp
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_egress_egress_proto_init() }
func file_egress_egress_proto_init() {
	if File_egress_egress_proto != nil {
		return
	}
	file_egress_egress_proto_msgTypes[2].OneofWrappers = []any{
		(*FileOutput_S3)(nil),
		(*FileOutput_AliOss)(nil),
	}
	file_egress_egress_proto_msgTypes[3].OneofWrappers = []any{
		(*SegmentOutput_S3)(nil),
		(*SegmentOutput_AliOss)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egress_egress_proto_rawDesc), len(file_egress_egress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egress_egress_proto_goTypes,
		DependencyIndexes: file_egress_egress_proto_depIdxs,
		MessageInfos:      file_egress_egress_proto_msgTypes,
	}.Build()
	File_egress_egress_proto = out.File
	file_egress_egress_proto_goTypes = nil
	file_egress_egress_proto_depIdxs = nil
}
