// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: egress/egress.proto

package egress

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressService_StartRoomRecording_FullMethodName  = "/openim.egress.EgressService/StartRoomRecording"
	EgressService_StartTrackRecording_FullMethodName = "/openim.egress.EgressService/StartTrackRecording"
	EgressService_StopRecording_FullMethodName       = "/openim.egress.EgressService/StopRecording"
	EgressService_ListRecordings_FullMethodName      = "/openim.egress.EgressService/ListRecordings"
	EgressService_UpdateLayout_FullMethodName        = "/openim.egress.EgressService/UpdateLayout"
	EgressService_UpdateStream_FullMethodName        = "/openim.egress.EgressService/UpdateStream"
)

// EgressServiceClient is the client API for EgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgressServiceClient interface {
	// 房间合成录制（整个房间画面）
	StartRoomRecording(ctx context.Context, in *StartRoomRecordingReq, opts ...grpc.CallOption) (*StartRoomRecordingResp, error)
	// 轨道合成录制（单参与者音视频）
	StartTrackRecording(ctx context.Context, in *StartTrackRecordingReq, opts ...grpc.CallOption) (*StartTrackRecordingResp, error)
	// 停止录制/推流
	StopRecording(ctx context.Context, in *StopRecordingReq, opts ...grpc.CallOption) (*StopRecordingResp, error)
	// 查询录制列表
	ListRecordings(ctx context.Context, in *ListRecordingsReq, opts ...grpc.CallOption) (*ListRecordingsResp, error)
	// 更新录制布局
	UpdateLayout(ctx context.Context, in *UpdateLayoutReq, opts ...grpc.CallOption) (*UpdateLayoutResp, error)
	// 更新推流地址
	UpdateStream(ctx context.Context, in *UpdateStreamReq, opts ...grpc.CallOption) (*UpdateStreamResp, error)
}

type egressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressServiceClient(cc grpc.ClientConnInterface) EgressServiceClient {
	return &egressServiceClient{cc}
}

func (c *egressServiceClient) StartRoomRecording(ctx context.Context, in *StartRoomRecordingReq, opts ...grpc.CallOption) (*StartRoomRecordingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRoomRecordingResp)
	err := c.cc.Invoke(ctx, EgressService_StartRoomRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressServiceClient) StartTrackRecording(ctx context.Context, in *StartTrackRecordingReq, opts ...grpc.CallOption) (*StartTrackRecordingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTrackRecordingResp)
	err := c.cc.Invoke(ctx, EgressService_StartTrackRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressServiceClient) StopRecording(ctx context.Context, in *StopRecordingReq, opts ...grpc.CallOption) (*StopRecordingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRecordingResp)
	err := c.cc.Invoke(ctx, EgressService_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressServiceClient) ListRecordings(ctx context.Context, in *ListRecordingsReq, opts ...grpc.CallOption) (*ListRecordingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordingsResp)
	err := c.cc.Invoke(ctx, EgressService_ListRecordings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressServiceClient) UpdateLayout(ctx context.Context, in *UpdateLayoutReq, opts ...grpc.CallOption) (*UpdateLayoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLayoutResp)
	err := c.cc.Invoke(ctx, EgressService_UpdateLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressServiceClient) UpdateStream(ctx context.Context, in *UpdateStreamReq, opts ...grpc.CallOption) (*UpdateStreamResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStreamResp)
	err := c.cc.Invoke(ctx, EgressService_UpdateStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressServiceServer is the server API for EgressService service.
// All implementations must embed UnimplementedEgressServiceServer
// for forward compatibility.
type EgressServiceServer interface {
	// 房间合成录制（整个房间画面）
	StartRoomRecording(context.Context, *StartRoomRecordingReq) (*StartRoomRecordingResp, error)
	// 轨道合成录制（单参与者音视频）
	StartTrackRecording(context.Context, *StartTrackRecordingReq) (*StartTrackRecordingResp, error)
	// 停止录制/推流
	StopRecording(context.Context, *StopRecordingReq) (*StopRecordingResp, error)
	// 查询录制列表
	ListRecordings(context.Context, *ListRecordingsReq) (*ListRecordingsResp, error)
	// 更新录制布局
	UpdateLayout(context.Context, *UpdateLayoutReq) (*UpdateLayoutResp, error)
	// 更新推流地址
	UpdateStream(context.Context, *UpdateStreamReq) (*UpdateStreamResp, error)
	mustEmbedUnimplementedEgressServiceServer()
}

// UnimplementedEgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressServiceServer struct{}

func (UnimplementedEgressServiceServer) StartRoomRecording(context.Context, *StartRoomRecordingReq) (*StartRoomRecordingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRoomRecording not implemented")
}
func (UnimplementedEgressServiceServer) StartTrackRecording(context.Context, *StartTrackRecordingReq) (*StartTrackRecordingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrackRecording not implemented")
}
func (UnimplementedEgressServiceServer) StopRecording(context.Context, *StopRecordingReq) (*StopRecordingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedEgressServiceServer) ListRecordings(context.Context, *ListRecordingsReq) (*ListRecordingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecordings not implemented")
}
func (UnimplementedEgressServiceServer) UpdateLayout(context.Context, *UpdateLayoutReq) (*UpdateLayoutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLayout not implemented")
}
func (UnimplementedEgressServiceServer) UpdateStream(context.Context, *UpdateStreamReq) (*UpdateStreamResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStream not implemented")
}
func (UnimplementedEgressServiceServer) mustEmbedUnimplementedEgressServiceServer() {}
func (UnimplementedEgressServiceServer) testEmbeddedByValue()                       {}

// UnsafeEgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressServiceServer will
// result in compilation errors.
type UnsafeEgressServiceServer interface {
	mustEmbedUnimplementedEgressServiceServer()
}

func RegisterEgressServiceServer(s grpc.ServiceRegistrar, srv EgressServiceServer) {
	// If the following call panics, it indicates UnimplementedEgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressService_ServiceDesc, srv)
}

func _EgressService_StartRoomRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRoomRecordingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).StartRoomRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_StartRoomRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).StartRoomRecording(ctx, req.(*StartRoomRecordingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressService_StartTrackRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTrackRecordingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).StartTrackRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_StartTrackRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).StartTrackRecording(ctx, req.(*StartTrackRecordingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressService_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).StopRecording(ctx, req.(*StopRecordingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressService_ListRecordings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).ListRecordings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_ListRecordings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).ListRecordings(ctx, req.(*ListRecordingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressService_UpdateLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLayoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).UpdateLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_UpdateLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).UpdateLayout(ctx, req.(*UpdateLayoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressService_UpdateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).UpdateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_UpdateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).UpdateStream(ctx, req.(*UpdateStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressService_ServiceDesc is the grpc.ServiceDesc for EgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.egress.EgressService",
	HandlerType: (*EgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRoomRecording",
			Handler:    _EgressService_StartRoomRecording_Handler,
		},
		{
			MethodName: "StartTrackRecording",
			Handler:    _EgressService_StartTrackRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _EgressService_StopRecording_Handler,
		},
		{
			MethodName: "ListRecordings",
			Handler:    _EgressService_ListRecordings_Handler,
		},
		{
			MethodName: "UpdateLayout",
			Handler:    _EgressService_UpdateLayout_Handler,
		},
		{
			MethodName: "UpdateStream",
			Handler:    _EgressService_UpdateStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egress/egress.proto",
}
