// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.3
// source: email/email.proto

package email

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Email_AddEmailAccount_FullMethodName    = "/openim.email.Email/AddEmailAccount"
	Email_UpdateEmailAccount_FullMethodName = "/openim.email.Email/UpdateEmailAccount"
	Email_DeleteEmailAccount_FullMethodName = "/openim.email.Email/DeleteEmailAccount"
	Email_GetEmailAccounts_FullMethodName   = "/openim.email.Email/GetEmailAccounts"
	Email_TestEmailAccount_FullMethodName   = "/openim.email.Email/TestEmailAccount"
	Email_GetEmailConfig_FullMethodName     = "/openim.email.Email/GetEmailConfig"
	Email_GetEmailFolders_FullMethodName    = "/openim.email.Email/GetEmailFolders"
	Email_CreateEmailFolder_FullMethodName  = "/openim.email.Email/CreateEmailFolder"
	Email_DeleteEmailFolder_FullMethodName  = "/openim.email.Email/DeleteEmailFolder"
	Email_SendEmail_FullMethodName          = "/openim.email.Email/SendEmail"
	Email_SaveDraft_FullMethodName          = "/openim.email.Email/SaveDraft"
	Email_GetEmails_FullMethodName          = "/openim.email.Email/GetEmails"
	Email_GetEmailDetail_FullMethodName     = "/openim.email.Email/GetEmailDetail"
	Email_DeleteEmails_FullMethodName       = "/openim.email.Email/DeleteEmails"
	Email_MoveEmails_FullMethodName         = "/openim.email.Email/MoveEmails"
	Email_MarkEmails_FullMethodName         = "/openim.email.Email/MarkEmails"
	Email_SyncEmails_FullMethodName         = "/openim.email.Email/SyncEmails"
	Email_GetUnreadCount_FullMethodName     = "/openim.email.Email/GetUnreadCount"
)

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailClient interface {
	// 账户管理
	AddEmailAccount(ctx context.Context, in *AddEmailAccountReq, opts ...grpc.CallOption) (*AddEmailAccountResp, error)
	UpdateEmailAccount(ctx context.Context, in *UpdateEmailAccountReq, opts ...grpc.CallOption) (*UpdateEmailAccountResp, error)
	DeleteEmailAccount(ctx context.Context, in *DeleteEmailAccountReq, opts ...grpc.CallOption) (*DeleteEmailAccountResp, error)
	GetEmailAccounts(ctx context.Context, in *GetEmailAccountsReq, opts ...grpc.CallOption) (*GetEmailAccountsResp, error)
	TestEmailAccount(ctx context.Context, in *TestEmailAccountReq, opts ...grpc.CallOption) (*TestEmailAccountResp, error)
	GetEmailConfig(ctx context.Context, in *GetEmailConfigReq, opts ...grpc.CallOption) (*GetEmailConfigResp, error)
	// 文件夹管理
	GetEmailFolders(ctx context.Context, in *GetEmailFoldersReq, opts ...grpc.CallOption) (*GetEmailFoldersResp, error)
	CreateEmailFolder(ctx context.Context, in *CreateEmailFolderReq, opts ...grpc.CallOption) (*CreateEmailFolderResp, error)
	DeleteEmailFolder(ctx context.Context, in *DeleteEmailFolderReq, opts ...grpc.CallOption) (*DeleteEmailFolderResp, error)
	// 邮件操作
	SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error)
	SaveDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*SaveDraftResp, error)
	GetEmails(ctx context.Context, in *GetEmailsReq, opts ...grpc.CallOption) (*GetEmailsResp, error)
	GetEmailDetail(ctx context.Context, in *GetEmailDetailReq, opts ...grpc.CallOption) (*GetEmailDetailResp, error)
	DeleteEmails(ctx context.Context, in *DeleteEmailsReq, opts ...grpc.CallOption) (*DeleteEmailsResp, error)
	MoveEmails(ctx context.Context, in *MoveEmailsReq, opts ...grpc.CallOption) (*MoveEmailsResp, error)
	MarkEmails(ctx context.Context, in *MarkEmailsReq, opts ...grpc.CallOption) (*MarkEmailsResp, error)
	SyncEmails(ctx context.Context, in *SyncEmailsReq, opts ...grpc.CallOption) (*SyncEmailsResp, error)
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
}

type emailClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailClient(cc grpc.ClientConnInterface) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) AddEmailAccount(ctx context.Context, in *AddEmailAccountReq, opts ...grpc.CallOption) (*AddEmailAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEmailAccountResp)
	err := c.cc.Invoke(ctx, Email_AddEmailAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) UpdateEmailAccount(ctx context.Context, in *UpdateEmailAccountReq, opts ...grpc.CallOption) (*UpdateEmailAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmailAccountResp)
	err := c.cc.Invoke(ctx, Email_UpdateEmailAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) DeleteEmailAccount(ctx context.Context, in *DeleteEmailAccountReq, opts ...grpc.CallOption) (*DeleteEmailAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmailAccountResp)
	err := c.cc.Invoke(ctx, Email_DeleteEmailAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmailAccounts(ctx context.Context, in *GetEmailAccountsReq, opts ...grpc.CallOption) (*GetEmailAccountsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailAccountsResp)
	err := c.cc.Invoke(ctx, Email_GetEmailAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) TestEmailAccount(ctx context.Context, in *TestEmailAccountReq, opts ...grpc.CallOption) (*TestEmailAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestEmailAccountResp)
	err := c.cc.Invoke(ctx, Email_TestEmailAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmailConfig(ctx context.Context, in *GetEmailConfigReq, opts ...grpc.CallOption) (*GetEmailConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailConfigResp)
	err := c.cc.Invoke(ctx, Email_GetEmailConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmailFolders(ctx context.Context, in *GetEmailFoldersReq, opts ...grpc.CallOption) (*GetEmailFoldersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailFoldersResp)
	err := c.cc.Invoke(ctx, Email_GetEmailFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) CreateEmailFolder(ctx context.Context, in *CreateEmailFolderReq, opts ...grpc.CallOption) (*CreateEmailFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEmailFolderResp)
	err := c.cc.Invoke(ctx, Email_CreateEmailFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) DeleteEmailFolder(ctx context.Context, in *DeleteEmailFolderReq, opts ...grpc.CallOption) (*DeleteEmailFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmailFolderResp)
	err := c.cc.Invoke(ctx, Email_DeleteEmailFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResp)
	err := c.cc.Invoke(ctx, Email_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SaveDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*SaveDraftResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDraftResp)
	err := c.cc.Invoke(ctx, Email_SaveDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmails(ctx context.Context, in *GetEmailsReq, opts ...grpc.CallOption) (*GetEmailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailsResp)
	err := c.cc.Invoke(ctx, Email_GetEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmailDetail(ctx context.Context, in *GetEmailDetailReq, opts ...grpc.CallOption) (*GetEmailDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailDetailResp)
	err := c.cc.Invoke(ctx, Email_GetEmailDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) DeleteEmails(ctx context.Context, in *DeleteEmailsReq, opts ...grpc.CallOption) (*DeleteEmailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmailsResp)
	err := c.cc.Invoke(ctx, Email_DeleteEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) MoveEmails(ctx context.Context, in *MoveEmailsReq, opts ...grpc.CallOption) (*MoveEmailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveEmailsResp)
	err := c.cc.Invoke(ctx, Email_MoveEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) MarkEmails(ctx context.Context, in *MarkEmailsReq, opts ...grpc.CallOption) (*MarkEmailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkEmailsResp)
	err := c.cc.Invoke(ctx, Email_MarkEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SyncEmails(ctx context.Context, in *SyncEmailsReq, opts ...grpc.CallOption) (*SyncEmailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncEmailsResp)
	err := c.cc.Invoke(ctx, Email_SyncEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResp)
	err := c.cc.Invoke(ctx, Email_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
// All implementations must embed UnimplementedEmailServer
// for forward compatibility.
type EmailServer interface {
	// 账户管理
	AddEmailAccount(context.Context, *AddEmailAccountReq) (*AddEmailAccountResp, error)
	UpdateEmailAccount(context.Context, *UpdateEmailAccountReq) (*UpdateEmailAccountResp, error)
	DeleteEmailAccount(context.Context, *DeleteEmailAccountReq) (*DeleteEmailAccountResp, error)
	GetEmailAccounts(context.Context, *GetEmailAccountsReq) (*GetEmailAccountsResp, error)
	TestEmailAccount(context.Context, *TestEmailAccountReq) (*TestEmailAccountResp, error)
	GetEmailConfig(context.Context, *GetEmailConfigReq) (*GetEmailConfigResp, error)
	// 文件夹管理
	GetEmailFolders(context.Context, *GetEmailFoldersReq) (*GetEmailFoldersResp, error)
	CreateEmailFolder(context.Context, *CreateEmailFolderReq) (*CreateEmailFolderResp, error)
	DeleteEmailFolder(context.Context, *DeleteEmailFolderReq) (*DeleteEmailFolderResp, error)
	// 邮件操作
	SendEmail(context.Context, *SendEmailReq) (*SendEmailResp, error)
	SaveDraft(context.Context, *SaveDraftReq) (*SaveDraftResp, error)
	GetEmails(context.Context, *GetEmailsReq) (*GetEmailsResp, error)
	GetEmailDetail(context.Context, *GetEmailDetailReq) (*GetEmailDetailResp, error)
	DeleteEmails(context.Context, *DeleteEmailsReq) (*DeleteEmailsResp, error)
	MoveEmails(context.Context, *MoveEmailsReq) (*MoveEmailsResp, error)
	MarkEmails(context.Context, *MarkEmailsReq) (*MarkEmailsResp, error)
	SyncEmails(context.Context, *SyncEmailsReq) (*SyncEmailsResp, error)
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error)
	mustEmbedUnimplementedEmailServer()
}

// UnimplementedEmailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServer struct{}

func (UnimplementedEmailServer) AddEmailAccount(context.Context, *AddEmailAccountReq) (*AddEmailAccountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEmailAccount not implemented")
}
func (UnimplementedEmailServer) UpdateEmailAccount(context.Context, *UpdateEmailAccountReq) (*UpdateEmailAccountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEmailAccount not implemented")
}
func (UnimplementedEmailServer) DeleteEmailAccount(context.Context, *DeleteEmailAccountReq) (*DeleteEmailAccountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmailAccount not implemented")
}
func (UnimplementedEmailServer) GetEmailAccounts(context.Context, *GetEmailAccountsReq) (*GetEmailAccountsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailAccounts not implemented")
}
func (UnimplementedEmailServer) TestEmailAccount(context.Context, *TestEmailAccountReq) (*TestEmailAccountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestEmailAccount not implemented")
}
func (UnimplementedEmailServer) GetEmailConfig(context.Context, *GetEmailConfigReq) (*GetEmailConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailConfig not implemented")
}
func (UnimplementedEmailServer) GetEmailFolders(context.Context, *GetEmailFoldersReq) (*GetEmailFoldersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailFolders not implemented")
}
func (UnimplementedEmailServer) CreateEmailFolder(context.Context, *CreateEmailFolderReq) (*CreateEmailFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmailFolder not implemented")
}
func (UnimplementedEmailServer) DeleteEmailFolder(context.Context, *DeleteEmailFolderReq) (*DeleteEmailFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmailFolder not implemented")
}
func (UnimplementedEmailServer) SendEmail(context.Context, *SendEmailReq) (*SendEmailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailServer) SaveDraft(context.Context, *SaveDraftReq) (*SaveDraftResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDraft not implemented")
}
func (UnimplementedEmailServer) GetEmails(context.Context, *GetEmailsReq) (*GetEmailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmails not implemented")
}
func (UnimplementedEmailServer) GetEmailDetail(context.Context, *GetEmailDetailReq) (*GetEmailDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailDetail not implemented")
}
func (UnimplementedEmailServer) DeleteEmails(context.Context, *DeleteEmailsReq) (*DeleteEmailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmails not implemented")
}
func (UnimplementedEmailServer) MoveEmails(context.Context, *MoveEmailsReq) (*MoveEmailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveEmails not implemented")
}
func (UnimplementedEmailServer) MarkEmails(context.Context, *MarkEmailsReq) (*MarkEmailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkEmails not implemented")
}
func (UnimplementedEmailServer) SyncEmails(context.Context, *SyncEmailsReq) (*SyncEmailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncEmails not implemented")
}
func (UnimplementedEmailServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedEmailServer) mustEmbedUnimplementedEmailServer() {}
func (UnimplementedEmailServer) testEmbeddedByValue()               {}

// UnsafeEmailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServer will
// result in compilation errors.
type UnsafeEmailServer interface {
	mustEmbedUnimplementedEmailServer()
}

func RegisterEmailServer(s grpc.ServiceRegistrar, srv EmailServer) {
	// If the following call panics, it indicates UnimplementedEmailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Email_ServiceDesc, srv)
}

func _Email_AddEmailAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmailAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).AddEmailAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_AddEmailAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).AddEmailAccount(ctx, req.(*AddEmailAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_UpdateEmailAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).UpdateEmailAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_UpdateEmailAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).UpdateEmailAccount(ctx, req.(*UpdateEmailAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_DeleteEmailAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).DeleteEmailAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_DeleteEmailAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).DeleteEmailAccount(ctx, req.(*DeleteEmailAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmailAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailAccountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmailAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetEmailAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmailAccounts(ctx, req.(*GetEmailAccountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_TestEmailAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestEmailAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).TestEmailAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_TestEmailAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).TestEmailAccount(ctx, req.(*TestEmailAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmailConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmailConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetEmailConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmailConfig(ctx, req.(*GetEmailConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmailFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailFoldersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmailFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetEmailFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmailFolders(ctx, req.(*GetEmailFoldersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_CreateEmailFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).CreateEmailFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_CreateEmailFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).CreateEmailFolder(ctx, req.(*CreateEmailFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_DeleteEmailFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).DeleteEmailFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_DeleteEmailFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).DeleteEmailFolder(ctx, req.(*DeleteEmailFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendEmail(ctx, req.(*SendEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SaveDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDraftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SaveDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SaveDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SaveDraft(ctx, req.(*SaveDraftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmails(ctx, req.(*GetEmailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmailDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmailDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetEmailDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmailDetail(ctx, req.(*GetEmailDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_DeleteEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).DeleteEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_DeleteEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).DeleteEmails(ctx, req.(*DeleteEmailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_MoveEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveEmailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).MoveEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_MoveEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).MoveEmails(ctx, req.(*MoveEmailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_MarkEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkEmailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).MarkEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_MarkEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).MarkEmails(ctx, req.(*MarkEmailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SyncEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncEmailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SyncEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_SyncEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SyncEmails(ctx, req.(*SyncEmailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Email_ServiceDesc is the grpc.ServiceDesc for Email service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Email_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEmailAccount",
			Handler:    _Email_AddEmailAccount_Handler,
		},
		{
			MethodName: "UpdateEmailAccount",
			Handler:    _Email_UpdateEmailAccount_Handler,
		},
		{
			MethodName: "DeleteEmailAccount",
			Handler:    _Email_DeleteEmailAccount_Handler,
		},
		{
			MethodName: "GetEmailAccounts",
			Handler:    _Email_GetEmailAccounts_Handler,
		},
		{
			MethodName: "TestEmailAccount",
			Handler:    _Email_TestEmailAccount_Handler,
		},
		{
			MethodName: "GetEmailConfig",
			Handler:    _Email_GetEmailConfig_Handler,
		},
		{
			MethodName: "GetEmailFolders",
			Handler:    _Email_GetEmailFolders_Handler,
		},
		{
			MethodName: "CreateEmailFolder",
			Handler:    _Email_CreateEmailFolder_Handler,
		},
		{
			MethodName: "DeleteEmailFolder",
			Handler:    _Email_DeleteEmailFolder_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _Email_SendEmail_Handler,
		},
		{
			MethodName: "SaveDraft",
			Handler:    _Email_SaveDraft_Handler,
		},
		{
			MethodName: "GetEmails",
			Handler:    _Email_GetEmails_Handler,
		},
		{
			MethodName: "GetEmailDetail",
			Handler:    _Email_GetEmailDetail_Handler,
		},
		{
			MethodName: "DeleteEmails",
			Handler:    _Email_DeleteEmails_Handler,
		},
		{
			MethodName: "MoveEmails",
			Handler:    _Email_MoveEmails_Handler,
		},
		{
			MethodName: "MarkEmails",
			Handler:    _Email_MarkEmails_Handler,
		},
		{
			MethodName: "SyncEmails",
			Handler:    _Email_SyncEmails_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _Email_GetUnreadCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email/email.proto",
}
