// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: meeting_room/meeting_room.proto

package meeting_room

import (
	sdkws "github.com/openimsdk/protocol/sdkws"
	wrapperspb "github.com/openimsdk/protocol/wrapperspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeetingRoomLocationInfo 会议室地点信息
type MeetingRoomLocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationID    string                 `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	ParentID      string                 `protobuf:"bytes,3,opt,name=parentID,proto3" json:"parentID"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level"` // 1=城市 2=大厦 3=楼层
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sortOrder,proto3" json:"sortOrder"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status"` // 1=启用 2=禁用
	CreateTime    int64                  `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime"`
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoomLocationInfo) Reset() {
	*x = MeetingRoomLocationInfo{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoomLocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoomLocationInfo) ProtoMessage() {}

func (x *MeetingRoomLocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoomLocationInfo.ProtoReflect.Descriptor instead.
func (*MeetingRoomLocationInfo) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{0}
}

func (x *MeetingRoomLocationInfo) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *MeetingRoomLocationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeetingRoomLocationInfo) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *MeetingRoomLocationInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MeetingRoomLocationInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *MeetingRoomLocationInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MeetingRoomLocationInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MeetingRoomLocationInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// MeetingRoomLocationTreeNode 地点树节点
type MeetingRoomLocationTreeNode struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	LocationID    string                         `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID"`
	Name          string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Level         int32                          `protobuf:"varint,3,opt,name=level,proto3" json:"level"`
	Status        int32                          `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	Children      []*MeetingRoomLocationTreeNode `protobuf:"bytes,5,rep,name=children,proto3" json:"children"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoomLocationTreeNode) Reset() {
	*x = MeetingRoomLocationTreeNode{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoomLocationTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoomLocationTreeNode) ProtoMessage() {}

func (x *MeetingRoomLocationTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoomLocationTreeNode.ProtoReflect.Descriptor instead.
func (*MeetingRoomLocationTreeNode) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{1}
}

func (x *MeetingRoomLocationTreeNode) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *MeetingRoomLocationTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeetingRoomLocationTreeNode) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MeetingRoomLocationTreeNode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MeetingRoomLocationTreeNode) GetChildren() []*MeetingRoomLocationTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// MeetingRoomInfo 会议室信息
type MeetingRoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	FullName      string                 `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName"`
	LocationID    string                 `protobuf:"bytes,4,opt,name=locationID,proto3" json:"locationID"`
	LocationPath  string                 `protobuf:"bytes,5,opt,name=locationPath,proto3" json:"locationPath"` // 地点全路径（如"深圳市-康利城6栋-7楼"）
	Capacity      int32                  `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity"`
	Equipment     []string               `protobuf:"bytes,7,rep,name=equipment,proto3" json:"equipment"` // tv/phone/projector/whiteboard/video
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status"` // 1=可用 2=停用
	SortOrder     int32                  `protobuf:"varint,10,opt,name=sortOrder,proto3" json:"sortOrder"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime"`
	UpdateTime    int64                  `protobuf:"varint,12,opt,name=updateTime,proto3" json:"updateTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoomInfo) Reset() {
	*x = MeetingRoomInfo{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoomInfo) ProtoMessage() {}

func (x *MeetingRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoomInfo.ProtoReflect.Descriptor instead.
func (*MeetingRoomInfo) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{2}
}

func (x *MeetingRoomInfo) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *MeetingRoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeetingRoomInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *MeetingRoomInfo) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *MeetingRoomInfo) GetLocationPath() string {
	if x != nil {
		return x.LocationPath
	}
	return ""
}

func (x *MeetingRoomInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *MeetingRoomInfo) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *MeetingRoomInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MeetingRoomInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MeetingRoomInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *MeetingRoomInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MeetingRoomInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// RoomBookingSlot 已预定时段
type RoomBookingSlot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScheduleID      string                 `protobuf:"bytes,1,opt,name=scheduleID,proto3" json:"scheduleID"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	CreatorUserID   string                 `protobuf:"bytes,3,opt,name=creatorUserID,proto3" json:"creatorUserID"`
	CreatorNickname string                 `protobuf:"bytes,4,opt,name=creatorNickname,proto3" json:"creatorNickname"`
	StartTime       int64                  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime"`
	EndTime         int64                  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomBookingSlot) Reset() {
	*x = RoomBookingSlot{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBookingSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBookingSlot) ProtoMessage() {}

func (x *RoomBookingSlot) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBookingSlot.ProtoReflect.Descriptor instead.
func (*RoomBookingSlot) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomBookingSlot) GetScheduleID() string {
	if x != nil {
		return x.ScheduleID
	}
	return ""
}

func (x *RoomBookingSlot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomBookingSlot) GetCreatorUserID() string {
	if x != nil {
		return x.CreatorUserID
	}
	return ""
}

func (x *RoomBookingSlot) GetCreatorNickname() string {
	if x != nil {
		return x.CreatorNickname
	}
	return ""
}

func (x *RoomBookingSlot) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RoomBookingSlot) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// MeetingRoomWithSlots 会议室及预定信息
type MeetingRoomWithSlots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *MeetingRoomInfo       `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo"`
	BookingSlots  []*RoomBookingSlot     `protobuf:"bytes,2,rep,name=bookingSlots,proto3" json:"bookingSlots"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoomWithSlots) Reset() {
	*x = MeetingRoomWithSlots{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoomWithSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoomWithSlots) ProtoMessage() {}

func (x *MeetingRoomWithSlots) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoomWithSlots.ProtoReflect.Descriptor instead.
func (*MeetingRoomWithSlots) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{4}
}

func (x *MeetingRoomWithSlots) GetRoomInfo() *MeetingRoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *MeetingRoomWithSlots) GetBookingSlots() []*RoomBookingSlot {
	if x != nil {
		return x.BookingSlots
	}
	return nil
}

// RoomAvailabilityEntry 单个房间的可用性信息
type RoomAvailabilityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID"`
	BookingSlots  []*RoomBookingSlot     `protobuf:"bytes,2,rep,name=bookingSlots,proto3" json:"bookingSlots"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomAvailabilityEntry) Reset() {
	*x = RoomAvailabilityEntry{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomAvailabilityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAvailabilityEntry) ProtoMessage() {}

func (x *RoomAvailabilityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAvailabilityEntry.ProtoReflect.Descriptor instead.
func (*RoomAvailabilityEntry) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomAvailabilityEntry) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *RoomAvailabilityEntry) GetBookingSlots() []*RoomBookingSlot {
	if x != nil {
		return x.BookingSlots
	}
	return nil
}

// 获取地点树
type GetMeetingRoomLocationTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"` // 0=全部 1=仅启用（默认1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomLocationTreeReq) Reset() {
	*x = GetMeetingRoomLocationTreeReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomLocationTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomLocationTreeReq) ProtoMessage() {}

func (x *GetMeetingRoomLocationTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomLocationTreeReq.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomLocationTreeReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetMeetingRoomLocationTreeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetMeetingRoomLocationTreeResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Tree          []*MeetingRoomLocationTreeNode `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomLocationTreeResp) Reset() {
	*x = GetMeetingRoomLocationTreeResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomLocationTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomLocationTreeResp) ProtoMessage() {}

func (x *GetMeetingRoomLocationTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomLocationTreeResp.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomLocationTreeResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetMeetingRoomLocationTreeResp) GetTree() []*MeetingRoomLocationTreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

// 获取会议室列表（筛选）
type GetMeetingRoomListReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	LocationID    string                   `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID"`        // 地点ID（任意层级）
	Date          int64                    `protobuf:"varint,2,opt,name=date,proto3" json:"date"`                   // 查询日期（时间戳）
	StartTime     int64                    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime"`         // 可用时段开始时间
	Duration      int32                    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration"`           // 时长（分钟）
	CapacityRange int32                    `protobuf:"varint,5,opt,name=capacityRange,proto3" json:"capacityRange"` // 1=12人以下 2=13-20人 3=20人以上
	Equipment     []string                 `protobuf:"bytes,6,rep,name=equipment,proto3" json:"equipment"`          // 设备要求（AND关系）
	Keyword       string                   `protobuf:"bytes,7,opt,name=keyword,proto3" json:"keyword"`              // 搜索关键词
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,8,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomListReq) Reset() {
	*x = GetMeetingRoomListReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomListReq) ProtoMessage() {}

func (x *GetMeetingRoomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomListReq.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomListReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{8}
}

func (x *GetMeetingRoomListReq) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *GetMeetingRoomListReq) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GetMeetingRoomListReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMeetingRoomListReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GetMeetingRoomListReq) GetCapacityRange() int32 {
	if x != nil {
		return x.CapacityRange
	}
	return 0
}

func (x *GetMeetingRoomListReq) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *GetMeetingRoomListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetMeetingRoomListReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetMeetingRoomListResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Rooms         []*MeetingRoomWithSlots `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomListResp) Reset() {
	*x = GetMeetingRoomListResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomListResp) ProtoMessage() {}

func (x *GetMeetingRoomListResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomListResp.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomListResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeetingRoomListResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMeetingRoomListResp) GetRooms() []*MeetingRoomWithSlots {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 获取会议室详情
type GetMeetingRoomDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomDetailReq) Reset() {
	*x = GetMeetingRoomDetailReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomDetailReq) ProtoMessage() {}

func (x *GetMeetingRoomDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomDetailReq.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomDetailReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{10}
}

func (x *GetMeetingRoomDetailReq) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type GetMeetingRoomDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *MeetingRoomInfo       `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomDetailResp) Reset() {
	*x = GetMeetingRoomDetailResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomDetailResp) ProtoMessage() {}

func (x *GetMeetingRoomDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomDetailResp.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomDetailResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{11}
}

func (x *GetMeetingRoomDetailResp) GetRoomInfo() *MeetingRoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 获取会议室可用时段
type GetMeetingRoomAvailabilityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIDs       []string               `protobuf:"bytes,1,rep,name=roomIDs,proto3" json:"roomIDs"`
	Date          int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRoomAvailabilityReq) Reset() {
	*x = GetMeetingRoomAvailabilityReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomAvailabilityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomAvailabilityReq) ProtoMessage() {}

func (x *GetMeetingRoomAvailabilityReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomAvailabilityReq.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomAvailabilityReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{12}
}

func (x *GetMeetingRoomAvailabilityReq) GetRoomIDs() []string {
	if x != nil {
		return x.RoomIDs
	}
	return nil
}

func (x *GetMeetingRoomAvailabilityReq) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type GetMeetingRoomAvailabilityResp struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	RoomAvailability []*RoomAvailabilityEntry `protobuf:"bytes,1,rep,name=roomAvailability,proto3" json:"roomAvailability"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMeetingRoomAvailabilityResp) Reset() {
	*x = GetMeetingRoomAvailabilityResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRoomAvailabilityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRoomAvailabilityResp) ProtoMessage() {}

func (x *GetMeetingRoomAvailabilityResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRoomAvailabilityResp.ProtoReflect.Descriptor instead.
func (*GetMeetingRoomAvailabilityResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{13}
}

func (x *GetMeetingRoomAvailabilityResp) GetRoomAvailability() []*RoomAvailabilityEntry {
	if x != nil {
		return x.RoomAvailability
	}
	return nil
}

// 创建地点
type CreateMeetingRoomLocationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	ParentID      string                 `protobuf:"bytes,2,opt,name=parentID,proto3" json:"parentID"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sortOrder,proto3" json:"sortOrder"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRoomLocationReq) Reset() {
	*x = CreateMeetingRoomLocationReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRoomLocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRoomLocationReq) ProtoMessage() {}

func (x *CreateMeetingRoomLocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRoomLocationReq.ProtoReflect.Descriptor instead.
func (*CreateMeetingRoomLocationReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{14}
}

func (x *CreateMeetingRoomLocationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMeetingRoomLocationReq) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *CreateMeetingRoomLocationReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateMeetingRoomLocationReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateMeetingRoomLocationResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Location      *MeetingRoomLocationInfo `protobuf:"bytes,1,opt,name=location,proto3" json:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRoomLocationResp) Reset() {
	*x = CreateMeetingRoomLocationResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRoomLocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRoomLocationResp) ProtoMessage() {}

func (x *CreateMeetingRoomLocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRoomLocationResp.ProtoReflect.Descriptor instead.
func (*CreateMeetingRoomLocationResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{15}
}

func (x *CreateMeetingRoomLocationResp) GetLocation() *MeetingRoomLocationInfo {
	if x != nil {
		return x.Location
	}
	return nil
}

// 更新地点
type UpdateMeetingRoomLocationReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	LocationID    string                  `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	SortOrder     *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=sortOrder,proto3" json:"sortOrder"`
	Status        *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingRoomLocationReq) Reset() {
	*x = UpdateMeetingRoomLocationReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRoomLocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRoomLocationReq) ProtoMessage() {}

func (x *UpdateMeetingRoomLocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRoomLocationReq.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRoomLocationReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMeetingRoomLocationReq) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *UpdateMeetingRoomLocationReq) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateMeetingRoomLocationReq) GetSortOrder() *wrapperspb.Int32Value {
	if x != nil {
		return x.SortOrder
	}
	return nil
}

func (x *UpdateMeetingRoomLocationReq) GetStatus() *wrapperspb.Int32Value {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateMeetingRoomLocationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingRoomLocationResp) Reset() {
	*x = UpdateMeetingRoomLocationResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRoomLocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRoomLocationResp) ProtoMessage() {}

func (x *UpdateMeetingRoomLocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRoomLocationResp.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRoomLocationResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{17}
}

// 删除地点
type DeleteMeetingRoomLocationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIDs   []string               `protobuf:"bytes,1,rep,name=locationIDs,proto3" json:"locationIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeetingRoomLocationReq) Reset() {
	*x = DeleteMeetingRoomLocationReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeetingRoomLocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRoomLocationReq) ProtoMessage() {}

func (x *DeleteMeetingRoomLocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRoomLocationReq.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRoomLocationReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteMeetingRoomLocationReq) GetLocationIDs() []string {
	if x != nil {
		return x.LocationIDs
	}
	return nil
}

type DeleteMeetingRoomLocationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeetingRoomLocationResp) Reset() {
	*x = DeleteMeetingRoomLocationResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeetingRoomLocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRoomLocationResp) ProtoMessage() {}

func (x *DeleteMeetingRoomLocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRoomLocationResp.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRoomLocationResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{19}
}

// 获取地点树（管理端，支持全部状态筛选）
type GetAdminMeetingRoomLocationTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"` // 0=全部 1=仅启用 2=仅禁用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminMeetingRoomLocationTreeReq) Reset() {
	*x = GetAdminMeetingRoomLocationTreeReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminMeetingRoomLocationTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminMeetingRoomLocationTreeReq) ProtoMessage() {}

func (x *GetAdminMeetingRoomLocationTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminMeetingRoomLocationTreeReq.ProtoReflect.Descriptor instead.
func (*GetAdminMeetingRoomLocationTreeReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{20}
}

func (x *GetAdminMeetingRoomLocationTreeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetAdminMeetingRoomLocationTreeResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Tree          []*MeetingRoomLocationTreeNode `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminMeetingRoomLocationTreeResp) Reset() {
	*x = GetAdminMeetingRoomLocationTreeResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminMeetingRoomLocationTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminMeetingRoomLocationTreeResp) ProtoMessage() {}

func (x *GetAdminMeetingRoomLocationTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminMeetingRoomLocationTreeResp.ProtoReflect.Descriptor instead.
func (*GetAdminMeetingRoomLocationTreeResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{21}
}

func (x *GetAdminMeetingRoomLocationTreeResp) GetTree() []*MeetingRoomLocationTreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

// 创建会议室
type CreateMeetingRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName"`
	LocationID    string                 `protobuf:"bytes,3,opt,name=locationID,proto3" json:"locationID"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity"`
	Equipment     []string               `protobuf:"bytes,5,rep,name=equipment,proto3" json:"equipment"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sortOrder,proto3" json:"sortOrder"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRoomReq) Reset() {
	*x = CreateMeetingRoomReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRoomReq) ProtoMessage() {}

func (x *CreateMeetingRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRoomReq.ProtoReflect.Descriptor instead.
func (*CreateMeetingRoomReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{22}
}

func (x *CreateMeetingRoomReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMeetingRoomReq) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateMeetingRoomReq) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *CreateMeetingRoomReq) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateMeetingRoomReq) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *CreateMeetingRoomReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMeetingRoomReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateMeetingRoomReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateMeetingRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *MeetingRoomInfo       `protobuf:"bytes,1,opt,name=room,proto3" json:"room"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRoomResp) Reset() {
	*x = CreateMeetingRoomResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRoomResp) ProtoMessage() {}

func (x *CreateMeetingRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRoomResp.ProtoReflect.Descriptor instead.
func (*CreateMeetingRoomResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{23}
}

func (x *CreateMeetingRoomResp) GetRoom() *MeetingRoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

// 更新会议室
type UpdateMeetingRoomReq struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RoomID         string                  `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID"`
	Name           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	FullName       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName"`
	LocationID     *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=locationID,proto3" json:"locationID"`
	Capacity       *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity"`
	Equipment      []string                `protobuf:"bytes,6,rep,name=equipment,proto3" json:"equipment"`
	ClearEquipment bool                    `protobuf:"varint,7,opt,name=clearEquipment,proto3" json:"clearEquipment"` // 当 equipment 为空时，true 表示清空设备，false 表示不修改
	Description    *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=description,proto3" json:"description"`
	SortOrder      *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=sortOrder,proto3" json:"sortOrder"`
	Status         *wrapperspb.Int32Value  `protobuf:"bytes,10,opt,name=status,proto3" json:"status"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMeetingRoomReq) Reset() {
	*x = UpdateMeetingRoomReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRoomReq) ProtoMessage() {}

func (x *UpdateMeetingRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRoomReq.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRoomReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateMeetingRoomReq) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *UpdateMeetingRoomReq) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetFullName() *wrapperspb.StringValue {
	if x != nil {
		return x.FullName
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetLocationID() *wrapperspb.StringValue {
	if x != nil {
		return x.LocationID
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetCapacity() *wrapperspb.Int32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetClearEquipment() bool {
	if x != nil {
		return x.ClearEquipment
	}
	return false
}

func (x *UpdateMeetingRoomReq) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetSortOrder() *wrapperspb.Int32Value {
	if x != nil {
		return x.SortOrder
	}
	return nil
}

func (x *UpdateMeetingRoomReq) GetStatus() *wrapperspb.Int32Value {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateMeetingRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingRoomResp) Reset() {
	*x = UpdateMeetingRoomResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRoomResp) ProtoMessage() {}

func (x *UpdateMeetingRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRoomResp.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRoomResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{25}
}

// 删除会议室
type DeleteMeetingRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIDs       []string               `protobuf:"bytes,1,rep,name=roomIDs,proto3" json:"roomIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeetingRoomReq) Reset() {
	*x = DeleteMeetingRoomReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeetingRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRoomReq) ProtoMessage() {}

func (x *DeleteMeetingRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRoomReq.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRoomReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteMeetingRoomReq) GetRoomIDs() []string {
	if x != nil {
		return x.RoomIDs
	}
	return nil
}

type DeleteMeetingRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeetingRoomResp) Reset() {
	*x = DeleteMeetingRoomResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeetingRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRoomResp) ProtoMessage() {}

func (x *DeleteMeetingRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRoomResp.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRoomResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{27}
}

// 搜索会议室（管理端）
type SearchMeetingRoomReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keyword       string                   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	LocationID    string                   `protobuf:"bytes,2,opt,name=locationID,proto3" json:"locationID"`
	Status        int32                    `protobuf:"varint,3,opt,name=status,proto3" json:"status"`
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMeetingRoomReq) Reset() {
	*x = SearchMeetingRoomReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMeetingRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeetingRoomReq) ProtoMessage() {}

func (x *SearchMeetingRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeetingRoomReq.ProtoReflect.Descriptor instead.
func (*SearchMeetingRoomReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{28}
}

func (x *SearchMeetingRoomReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchMeetingRoomReq) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *SearchMeetingRoomReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchMeetingRoomReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchMeetingRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Rooms         []*MeetingRoomInfo     `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMeetingRoomResp) Reset() {
	*x = SearchMeetingRoomResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMeetingRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeetingRoomResp) ProtoMessage() {}

func (x *SearchMeetingRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeetingRoomResp.ProtoReflect.Descriptor instead.
func (*SearchMeetingRoomResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{29}
}

func (x *SearchMeetingRoomResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchMeetingRoomResp) GetRooms() []*MeetingRoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 批量获取会议室详情（内部 RPC，供 schedule/meeting 服务填充会议室信息）
type BatchGetRoomDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIDs       []string               `protobuf:"bytes,1,rep,name=roomIDs,proto3" json:"roomIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRoomDetailReq) Reset() {
	*x = BatchGetRoomDetailReq{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRoomDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRoomDetailReq) ProtoMessage() {}

func (x *BatchGetRoomDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRoomDetailReq.ProtoReflect.Descriptor instead.
func (*BatchGetRoomDetailReq) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{30}
}

func (x *BatchGetRoomDetailReq) GetRoomIDs() []string {
	if x != nil {
		return x.RoomIDs
	}
	return nil
}

type BatchGetRoomDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*MeetingRoomInfo     `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms"` // 按 roomID 匹配的会议室列表（不存在的 roomID 不返回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRoomDetailResp) Reset() {
	*x = BatchGetRoomDetailResp{}
	mi := &file_meeting_room_meeting_room_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRoomDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRoomDetailResp) ProtoMessage() {}

func (x *BatchGetRoomDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_room_meeting_room_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRoomDetailResp.ProtoReflect.Descriptor instead.
func (*BatchGetRoomDetailResp) Descriptor() ([]byte, []int) {
	return file_meeting_room_meeting_room_proto_rawDescGZIP(), []int{31}
}

func (x *BatchGetRoomDetailResp) GetRooms() []*MeetingRoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_meeting_room_meeting_room_proto protoreflect.FileDescriptor

const file_meeting_room_meeting_room_proto_rawDesc = "" +
	"\n" +
	"\x1fmeeting_room/meeting_room.proto\x12\x13openim.meeting_room\x1a\x11sdkws/sdkws.proto\x1a\x1bwrapperspb/wrapperspb.proto\"\xf5\x01\n" +
	"\x17MeetingRoomLocationInfo\x12\x1e\n" +
	"\n" +
	"locationID\x18\x01 \x01(\tR\n" +
	"locationID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bparentID\x18\x03 \x01(\tR\bparentID\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1c\n" +
	"\tsortOrder\x18\x05 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\a \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\b \x01(\x03R\n" +
	"updateTime\"\xcd\x01\n" +
	"\x1bMeetingRoomLocationTreeNode\x12\x1e\n" +
	"\n" +
	"locationID\x18\x01 \x01(\tR\n" +
	"locationID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12L\n" +
	"\bchildren\x18\x05 \x03(\v20.openim.meeting_room.MeetingRoomLocationTreeNodeR\bchildren\"\xef\x02\n" +
	"\x0fMeetingRoomInfo\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bfullName\x18\x03 \x01(\tR\bfullName\x12\x1e\n" +
	"\n" +
	"locationID\x18\x04 \x01(\tR\n" +
	"locationID\x12\"\n" +
	"\flocationPath\x18\x05 \x01(\tR\flocationPath\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x05R\bcapacity\x12\x1c\n" +
	"\tequipment\x18\a \x03(\tR\tequipment\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1c\n" +
	"\tsortOrder\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x1e\n" +
	"\n" +
	"createTime\x18\v \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\f \x01(\x03R\n" +
	"updateTime\"\xcf\x01\n" +
	"\x0fRoomBookingSlot\x12\x1e\n" +
	"\n" +
	"scheduleID\x18\x01 \x01(\tR\n" +
	"scheduleID\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12$\n" +
	"\rcreatorUserID\x18\x03 \x01(\tR\rcreatorUserID\x12(\n" +
	"\x0fcreatorNickname\x18\x04 \x01(\tR\x0fcreatorNickname\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\x03R\aendTime\"\xa2\x01\n" +
	"\x14MeetingRoomWithSlots\x12@\n" +
	"\broomInfo\x18\x01 \x01(\v2$.openim.meeting_room.MeetingRoomInfoR\broomInfo\x12H\n" +
	"\fbookingSlots\x18\x02 \x03(\v2$.openim.meeting_room.RoomBookingSlotR\fbookingSlots\"y\n" +
	"\x15RoomAvailabilityEntry\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x12H\n" +
	"\fbookingSlots\x18\x02 \x03(\v2$.openim.meeting_room.RoomBookingSlotR\fbookingSlots\"7\n" +
	"\x1dGetMeetingRoomLocationTreeReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"f\n" +
	"\x1eGetMeetingRoomLocationTreeResp\x12D\n" +
	"\x04tree\x18\x01 \x03(\v20.openim.meeting_room.MeetingRoomLocationTreeNodeR\x04tree\"\xa4\x02\n" +
	"\x15GetMeetingRoomListReq\x12\x1e\n" +
	"\n" +
	"locationID\x18\x01 \x01(\tR\n" +
	"locationID\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\x03R\tstartTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12$\n" +
	"\rcapacityRange\x18\x05 \x01(\x05R\rcapacityRange\x12\x1c\n" +
	"\tequipment\x18\x06 \x03(\tR\tequipment\x12\x18\n" +
	"\akeyword\x18\a \x01(\tR\akeyword\x12?\n" +
	"\n" +
	"pagination\x18\b \x01(\v2\x1f.openim.sdkws.RequestPaginationR\n" +
	"pagination\"o\n" +
	"\x16GetMeetingRoomListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12?\n" +
	"\x05rooms\x18\x02 \x03(\v2).openim.meeting_room.MeetingRoomWithSlotsR\x05rooms\"1\n" +
	"\x17GetMeetingRoomDetailReq\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\"\\\n" +
	"\x18GetMeetingRoomDetailResp\x12@\n" +
	"\broomInfo\x18\x01 \x01(\v2$.openim.meeting_room.MeetingRoomInfoR\broomInfo\"M\n" +
	"\x1dGetMeetingRoomAvailabilityReq\x12\x18\n" +
	"\aroomIDs\x18\x01 \x03(\tR\aroomIDs\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\"x\n" +
	"\x1eGetMeetingRoomAvailabilityResp\x12V\n" +
	"\x10roomAvailability\x18\x01 \x03(\v2*.openim.meeting_room.RoomAvailabilityEntryR\x10roomAvailability\"\x84\x01\n" +
	"\x1cCreateMeetingRoomLocationReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bparentID\x18\x02 \x01(\tR\bparentID\x12\x1c\n" +
	"\tsortOrder\x18\x03 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"i\n" +
	"\x1dCreateMeetingRoomLocationResp\x12H\n" +
	"\blocation\x18\x01 \x01(\v2,.openim.meeting_room.MeetingRoomLocationInfoR\blocation\"\xe0\x01\n" +
	"\x1cUpdateMeetingRoomLocationReq\x12\x1e\n" +
	"\n" +
	"locationID\x18\x01 \x01(\tR\n" +
	"locationID\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.openim.protobuf.StringValueR\x04name\x129\n" +
	"\tsortOrder\x18\x03 \x01(\v2\x1b.openim.protobuf.Int32ValueR\tsortOrder\x123\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.openim.protobuf.Int32ValueR\x06status\"\x1f\n" +
	"\x1dUpdateMeetingRoomLocationResp\"@\n" +
	"\x1cDeleteMeetingRoomLocationReq\x12 \n" +
	"\vlocationIDs\x18\x01 \x03(\tR\vlocationIDs\"\x1f\n" +
	"\x1dDeleteMeetingRoomLocationResp\"<\n" +
	"\"GetAdminMeetingRoomLocationTreeReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"k\n" +
	"#GetAdminMeetingRoomLocationTreeResp\x12D\n" +
	"\x04tree\x18\x01 \x03(\v20.openim.meeting_room.MeetingRoomLocationTreeNodeR\x04tree\"\xf8\x01\n" +
	"\x14CreateMeetingRoomReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1e\n" +
	"\n" +
	"locationID\x18\x03 \x01(\tR\n" +
	"locationID\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1c\n" +
	"\tequipment\x18\x05 \x03(\tR\tequipment\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\tsortOrder\x18\a \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"Q\n" +
	"\x15CreateMeetingRoomResp\x128\n" +
	"\x04room\x18\x01 \x01(\v2$.openim.meeting_room.MeetingRoomInfoR\x04room\"\x87\x04\n" +
	"\x14UpdateMeetingRoomReq\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.openim.protobuf.StringValueR\x04name\x128\n" +
	"\bfullName\x18\x03 \x01(\v2\x1c.openim.protobuf.StringValueR\bfullName\x12<\n" +
	"\n" +
	"locationID\x18\x04 \x01(\v2\x1c.openim.protobuf.StringValueR\n" +
	"locationID\x127\n" +
	"\bcapacity\x18\x05 \x01(\v2\x1b.openim.protobuf.Int32ValueR\bcapacity\x12\x1c\n" +
	"\tequipment\x18\x06 \x03(\tR\tequipment\x12&\n" +
	"\x0eclearEquipment\x18\a \x01(\bR\x0eclearEquipment\x12>\n" +
	"\vdescription\x18\b \x01(\v2\x1c.openim.protobuf.StringValueR\vdescription\x129\n" +
	"\tsortOrder\x18\t \x01(\v2\x1b.openim.protobuf.Int32ValueR\tsortOrder\x123\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1b.openim.protobuf.Int32ValueR\x06status\"\x17\n" +
	"\x15UpdateMeetingRoomResp\"0\n" +
	"\x14DeleteMeetingRoomReq\x12\x18\n" +
	"\aroomIDs\x18\x01 \x03(\tR\aroomIDs\"\x17\n" +
	"\x15DeleteMeetingRoomResp\"\xa9\x01\n" +
	"\x14SearchMeetingRoomReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1e\n" +
	"\n" +
	"locationID\x18\x02 \x01(\tR\n" +
	"locationID\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.openim.sdkws.RequestPaginationR\n" +
	"pagination\"i\n" +
	"\x15SearchMeetingRoomResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12:\n" +
	"\x05rooms\x18\x02 \x03(\v2$.openim.meeting_room.MeetingRoomInfoR\x05rooms\"1\n" +
	"\x15BatchGetRoomDetailReq\x12\x18\n" +
	"\aroomIDs\x18\x01 \x03(\tR\aroomIDs\"T\n" +
	"\x16BatchGetRoomDetailResp\x12:\n" +
	"\x05rooms\x18\x01 \x03(\v2$.openim.meeting_room.MeetingRoomInfoR\x05rooms2\xd5\x04\n" +
	"\x12MeetingRoomService\x12z\n" +
	"\x0fGetLocationTree\x122.openim.meeting_room.GetMeetingRoomLocationTreeReq\x1a3.openim.meeting_room.GetMeetingRoomLocationTreeResp\x12f\n" +
	"\vGetRoomList\x12*.openim.meeting_room.GetMeetingRoomListReq\x1a+.openim.meeting_room.GetMeetingRoomListResp\x12l\n" +
	"\rGetRoomDetail\x12,.openim.meeting_room.GetMeetingRoomDetailReq\x1a-.openim.meeting_room.GetMeetingRoomDetailResp\x12~\n" +
	"\x13GetRoomAvailability\x122.openim.meeting_room.GetMeetingRoomAvailabilityReq\x1a3.openim.meeting_room.GetMeetingRoomAvailabilityResp\x12m\n" +
	"\x12BatchGetRoomDetail\x12*.openim.meeting_room.BatchGetRoomDetailReq\x1a+.openim.meeting_room.BatchGetRoomDetailRespB,Z*github.com/openimsdk/protocol/meeting_roomb\x06proto3"

var (
	file_meeting_room_meeting_room_proto_rawDescOnce sync.Once
	file_meeting_room_meeting_room_proto_rawDescData []byte
)

func file_meeting_room_meeting_room_proto_rawDescGZIP() []byte {
	file_meeting_room_meeting_room_proto_rawDescOnce.Do(func() {
		file_meeting_room_meeting_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meeting_room_meeting_room_proto_rawDesc), len(file_meeting_room_meeting_room_proto_rawDesc)))
	})
	return file_meeting_room_meeting_room_proto_rawDescData
}

var file_meeting_room_meeting_room_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_meeting_room_meeting_room_proto_goTypes = []any{
	(*MeetingRoomLocationInfo)(nil),             // 0: openim.meeting_room.MeetingRoomLocationInfo
	(*MeetingRoomLocationTreeNode)(nil),         // 1: openim.meeting_room.MeetingRoomLocationTreeNode
	(*MeetingRoomInfo)(nil),                     // 2: openim.meeting_room.MeetingRoomInfo
	(*RoomBookingSlot)(nil),                     // 3: openim.meeting_room.RoomBookingSlot
	(*MeetingRoomWithSlots)(nil),                // 4: openim.meeting_room.MeetingRoomWithSlots
	(*RoomAvailabilityEntry)(nil),               // 5: openim.meeting_room.RoomAvailabilityEntry
	(*GetMeetingRoomLocationTreeReq)(nil),       // 6: openim.meeting_room.GetMeetingRoomLocationTreeReq
	(*GetMeetingRoomLocationTreeResp)(nil),      // 7: openim.meeting_room.GetMeetingRoomLocationTreeResp
	(*GetMeetingRoomListReq)(nil),               // 8: openim.meeting_room.GetMeetingRoomListReq
	(*GetMeetingRoomListResp)(nil),              // 9: openim.meeting_room.GetMeetingRoomListResp
	(*GetMeetingRoomDetailReq)(nil),             // 10: openim.meeting_room.GetMeetingRoomDetailReq
	(*GetMeetingRoomDetailResp)(nil),            // 11: openim.meeting_room.GetMeetingRoomDetailResp
	(*GetMeetingRoomAvailabilityReq)(nil),       // 12: openim.meeting_room.GetMeetingRoomAvailabilityReq
	(*GetMeetingRoomAvailabilityResp)(nil),      // 13: openim.meeting_room.GetMeetingRoomAvailabilityResp
	(*CreateMeetingRoomLocationReq)(nil),        // 14: openim.meeting_room.CreateMeetingRoomLocationReq
	(*CreateMeetingRoomLocationResp)(nil),       // 15: openim.meeting_room.CreateMeetingRoomLocationResp
	(*UpdateMeetingRoomLocationReq)(nil),        // 16: openim.meeting_room.UpdateMeetingRoomLocationReq
	(*UpdateMeetingRoomLocationResp)(nil),       // 17: openim.meeting_room.UpdateMeetingRoomLocationResp
	(*DeleteMeetingRoomLocationReq)(nil),        // 18: openim.meeting_room.DeleteMeetingRoomLocationReq
	(*DeleteMeetingRoomLocationResp)(nil),       // 19: openim.meeting_room.DeleteMeetingRoomLocationResp
	(*GetAdminMeetingRoomLocationTreeReq)(nil),  // 20: openim.meeting_room.GetAdminMeetingRoomLocationTreeReq
	(*GetAdminMeetingRoomLocationTreeResp)(nil), // 21: openim.meeting_room.GetAdminMeetingRoomLocationTreeResp
	(*CreateMeetingRoomReq)(nil),                // 22: openim.meeting_room.CreateMeetingRoomReq
	(*CreateMeetingRoomResp)(nil),               // 23: openim.meeting_room.CreateMeetingRoomResp
	(*UpdateMeetingRoomReq)(nil),                // 24: openim.meeting_room.UpdateMeetingRoomReq
	(*UpdateMeetingRoomResp)(nil),               // 25: openim.meeting_room.UpdateMeetingRoomResp
	(*DeleteMeetingRoomReq)(nil),                // 26: openim.meeting_room.DeleteMeetingRoomReq
	(*DeleteMeetingRoomResp)(nil),               // 27: openim.meeting_room.DeleteMeetingRoomResp
	(*SearchMeetingRoomReq)(nil),                // 28: openim.meeting_room.SearchMeetingRoomReq
	(*SearchMeetingRoomResp)(nil),               // 29: openim.meeting_room.SearchMeetingRoomResp
	(*BatchGetRoomDetailReq)(nil),               // 30: openim.meeting_room.BatchGetRoomDetailReq
	(*BatchGetRoomDetailResp)(nil),              // 31: openim.meeting_room.BatchGetRoomDetailResp
	(*sdkws.RequestPagination)(nil),             // 32: openim.sdkws.RequestPagination
	(*wrapperspb.StringValue)(nil),              // 33: openim.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),               // 34: openim.protobuf.Int32Value
}
var file_meeting_room_meeting_room_proto_depIdxs = []int32{
	1,  // 0: openim.meeting_room.MeetingRoomLocationTreeNode.children:type_name -> openim.meeting_room.MeetingRoomLocationTreeNode
	2,  // 1: openim.meeting_room.MeetingRoomWithSlots.roomInfo:type_name -> openim.meeting_room.MeetingRoomInfo
	3,  // 2: openim.meeting_room.MeetingRoomWithSlots.bookingSlots:type_name -> openim.meeting_room.RoomBookingSlot
	3,  // 3: openim.meeting_room.RoomAvailabilityEntry.bookingSlots:type_name -> openim.meeting_room.RoomBookingSlot
	1,  // 4: openim.meeting_room.GetMeetingRoomLocationTreeResp.tree:type_name -> openim.meeting_room.MeetingRoomLocationTreeNode
	32, // 5: openim.meeting_room.GetMeetingRoomListReq.pagination:type_name -> openim.sdkws.RequestPagination
	4,  // 6: openim.meeting_room.GetMeetingRoomListResp.rooms:type_name -> openim.meeting_room.MeetingRoomWithSlots
	2,  // 7: openim.meeting_room.GetMeetingRoomDetailResp.roomInfo:type_name -> openim.meeting_room.MeetingRoomInfo
	5,  // 8: openim.meeting_room.GetMeetingRoomAvailabilityResp.roomAvailability:type_name -> openim.meeting_room.RoomAvailabilityEntry
	0,  // 9: openim.meeting_room.CreateMeetingRoomLocationResp.location:type_name -> openim.meeting_room.MeetingRoomLocationInfo
	33, // 10: openim.meeting_room.UpdateMeetingRoomLocationReq.name:type_name -> openim.protobuf.StringValue
	34, // 11: openim.meeting_room.UpdateMeetingRoomLocationReq.sortOrder:type_name -> openim.protobuf.Int32Value
	34, // 12: openim.meeting_room.UpdateMeetingRoomLocationReq.status:type_name -> openim.protobuf.Int32Value
	1,  // 13: openim.meeting_room.GetAdminMeetingRoomLocationTreeResp.tree:type_name -> openim.meeting_room.MeetingRoomLocationTreeNode
	2,  // 14: openim.meeting_room.CreateMeetingRoomResp.room:type_name -> openim.meeting_room.MeetingRoomInfo
	33, // 15: openim.meeting_room.UpdateMeetingRoomReq.name:type_name -> openim.protobuf.StringValue
	33, // 16: openim.meeting_room.UpdateMeetingRoomReq.fullName:type_name -> openim.protobuf.StringValue
	33, // 17: openim.meeting_room.UpdateMeetingRoomReq.locationID:type_name -> openim.protobuf.StringValue
	34, // 18: openim.meeting_room.UpdateMeetingRoomReq.capacity:type_name -> openim.protobuf.Int32Value
	33, // 19: openim.meeting_room.UpdateMeetingRoomReq.description:type_name -> openim.protobuf.StringValue
	34, // 20: openim.meeting_room.UpdateMeetingRoomReq.sortOrder:type_name -> openim.protobuf.Int32Value
	34, // 21: openim.meeting_room.UpdateMeetingRoomReq.status:type_name -> openim.protobuf.Int32Value
	32, // 22: openim.meeting_room.SearchMeetingRoomReq.pagination:type_name -> openim.sdkws.RequestPagination
	2,  // 23: openim.meeting_room.SearchMeetingRoomResp.rooms:type_name -> openim.meeting_room.MeetingRoomInfo
	2,  // 24: openim.meeting_room.BatchGetRoomDetailResp.rooms:type_name -> openim.meeting_room.MeetingRoomInfo
	6,  // 25: openim.meeting_room.MeetingRoomService.GetLocationTree:input_type -> openim.meeting_room.GetMeetingRoomLocationTreeReq
	8,  // 26: openim.meeting_room.MeetingRoomService.GetRoomList:input_type -> openim.meeting_room.GetMeetingRoomListReq
	10, // 27: openim.meeting_room.MeetingRoomService.GetRoomDetail:input_type -> openim.meeting_room.GetMeetingRoomDetailReq
	12, // 28: openim.meeting_room.MeetingRoomService.GetRoomAvailability:input_type -> openim.meeting_room.GetMeetingRoomAvailabilityReq
	30, // 29: openim.meeting_room.MeetingRoomService.BatchGetRoomDetail:input_type -> openim.meeting_room.BatchGetRoomDetailReq
	7,  // 30: openim.meeting_room.MeetingRoomService.GetLocationTree:output_type -> openim.meeting_room.GetMeetingRoomLocationTreeResp
	9,  // 31: openim.meeting_room.MeetingRoomService.GetRoomList:output_type -> openim.meeting_room.GetMeetingRoomListResp
	11, // 32: openim.meeting_room.MeetingRoomService.GetRoomDetail:output_type -> openim.meeting_room.GetMeetingRoomDetailResp
	13, // 33: openim.meeting_room.MeetingRoomService.GetRoomAvailability:output_type -> openim.meeting_room.GetMeetingRoomAvailabilityResp
	31, // 34: openim.meeting_room.MeetingRoomService.BatchGetRoomDetail:output_type -> openim.meeting_room.BatchGetRoomDetailResp
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_meeting_room_meeting_room_proto_init() }
func file_meeting_room_meeting_room_proto_init() {
	if File_meeting_room_meeting_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_room_meeting_room_proto_rawDesc), len(file_meeting_room_meeting_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_room_meeting_room_proto_goTypes,
		DependencyIndexes: file_meeting_room_meeting_room_proto_depIdxs,
		MessageInfos:      file_meeting_room_meeting_room_proto_msgTypes,
	}.Build()
	File_meeting_room_meeting_room_proto = out.File
	file_meeting_room_meeting_room_proto_goTypes = nil
	file_meeting_room_meeting_room_proto_depIdxs = nil
}
