// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: oa/oa.proto

package oa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Oa_CreateCompany_FullMethodName                         = "/openim.oa.oa/CreateCompany"
	Oa_UpdateCompany_FullMethodName                         = "/openim.oa.oa/UpdateCompany"
	Oa_DeleteCompany_FullMethodName                         = "/openim.oa.oa/DeleteCompany"
	Oa_GetCompany_FullMethodName                            = "/openim.oa.oa/GetCompany"
	Oa_GetCompanies_FullMethodName                          = "/openim.oa.oa/GetCompanies"
	Oa_SearchCompany_FullMethodName                         = "/openim.oa.oa/SearchCompany"
	Oa_GetUserJoinedCompanies_FullMethodName                = "/openim.oa.oa/GetUserJoinedCompanies"
	Oa_GetMyJoinedCompanies_FullMethodName                  = "/openim.oa.oa/GetMyJoinedCompanies"
	Oa_GetDepartmentTree_FullMethodName                     = "/openim.oa.oa/GetDepartmentTree"
	Oa_SearchCompanyAndDepartment_FullMethodName            = "/openim.oa.oa/SearchCompanyAndDepartment"
	Oa_CreateDepartment_FullMethodName                      = "/openim.oa.oa/CreateDepartment"
	Oa_UpdateDepartment_FullMethodName                      = "/openim.oa.oa/UpdateDepartment"
	Oa_DeleteDepartment_FullMethodName                      = "/openim.oa.oa/DeleteDepartment"
	Oa_GetDepartment_FullMethodName                         = "/openim.oa.oa/GetDepartment"
	Oa_GetDepartments_FullMethodName                        = "/openim.oa.oa/GetDepartments"
	Oa_SearchDepartment_FullMethodName                      = "/openim.oa.oa/SearchDepartment"
	Oa_GetMembersByCompanyAndDepartment_FullMethodName      = "/openim.oa.oa/GetMembersByCompanyAndDepartment"
	Oa_GetAdminMembersByCompanyAndDepartment_FullMethodName = "/openim.oa.oa/GetAdminMembersByCompanyAndDepartment"
	Oa_CreateJobTitle_FullMethodName                        = "/openim.oa.oa/CreateJobTitle"
	Oa_UpdateJobTitle_FullMethodName                        = "/openim.oa.oa/UpdateJobTitle"
	Oa_DeleteJobTitle_FullMethodName                        = "/openim.oa.oa/DeleteJobTitle"
	Oa_GetJobTitle_FullMethodName                           = "/openim.oa.oa/GetJobTitle"
	Oa_GetJobTitles_FullMethodName                          = "/openim.oa.oa/GetJobTitles"
	Oa_SearchJobTitle_FullMethodName                        = "/openim.oa.oa/SearchJobTitle"
	Oa_GetJobTitlesByDepartment_FullMethodName              = "/openim.oa.oa/GetJobTitlesByDepartment"
	Oa_CreateJob_FullMethodName                             = "/openim.oa.oa/CreateJob"
	Oa_UpdateJob_FullMethodName                             = "/openim.oa.oa/UpdateJob"
	Oa_DeleteJob_FullMethodName                             = "/openim.oa.oa/DeleteJob"
	Oa_GetJob_FullMethodName                                = "/openim.oa.oa/GetJob"
	Oa_GetJobs_FullMethodName                               = "/openim.oa.oa/GetJobs"
	Oa_SearchJob_FullMethodName                             = "/openim.oa.oa/SearchJob"
	Oa_SyncJobFromJobTitle_FullMethodName                   = "/openim.oa.oa/SyncJobFromJobTitle"
	Oa_SyncOADataToChat_FullMethodName                      = "/openim.oa.oa/SyncOADataToChat"
	Oa_SyncOADepartmentToChat_FullMethodName                = "/openim.oa.oa/SyncOADepartmentToChat"
	Oa_SyncOAJobTitleToChat_FullMethodName                  = "/openim.oa.oa/SyncOAJobTitleToChat"
	Oa_SyncOACompanyToChat_FullMethodName                   = "/openim.oa.oa/SyncOACompanyToChat"
	Oa_SyncJobToChat_FullMethodName                         = "/openim.oa.oa/SyncJobToChat"
	Oa_SyncOAUserToChat_FullMethodName                      = "/openim.oa.oa/SyncOAUserToChat"
)

// OaClient is the client API for Oa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OA RPC 服务（包含公司、部门、职位管理）
type OaClient interface {
	// ========== 公司相关接口 ==========
	// 创建公司
	CreateCompany(ctx context.Context, in *CreateCompanyReq, opts ...grpc.CallOption) (*CreateCompanyResp, error)
	// 更新公司
	UpdateCompany(ctx context.Context, in *UpdateCompanyReq, opts ...grpc.CallOption) (*UpdateCompanyResp, error)
	// 删除公司
	DeleteCompany(ctx context.Context, in *DeleteCompanyReq, opts ...grpc.CallOption) (*DeleteCompanyResp, error)
	// 获取单个公司
	GetCompany(ctx context.Context, in *GetCompanyReq, opts ...grpc.CallOption) (*GetCompanyResp, error)
	// 批量获取公司
	GetCompanies(ctx context.Context, in *GetCompaniesReq, opts ...grpc.CallOption) (*GetCompaniesResp, error)
	// 搜索公司
	SearchCompany(ctx context.Context, in *SearchCompanyReq, opts ...grpc.CallOption) (*SearchCompanyResp, error)
	// 获取用户加入的企业（不包含部门信息，部门通过 GetDepartmentTree 获取）
	GetUserJoinedCompanies(ctx context.Context, in *GetUserJoinedCompaniesReq, opts ...grpc.CallOption) (*GetUserJoinedCompaniesResp, error)
	// 获取我加入的企业（只返回企业基本信息，不含部门，从上下文获取当前用户）
	GetMyJoinedCompanies(ctx context.Context, in *GetMyJoinedCompaniesReq, opts ...grpc.CallOption) (*GetMyJoinedCompaniesResp, error)
	// 获取部门树（统一接口：如果department_id为空，返回企业的根部门列表；否则返回该部门的子部门列表）
	GetDepartmentTree(ctx context.Context, in *GetDepartmentTreeReq, opts ...grpc.CallOption) (*GetDepartmentTreeResp, error)
	// 搜索企业和部门（返回树形结构）
	SearchCompanyAndDepartment(ctx context.Context, in *SearchCompanyAndDepartmentReq, opts ...grpc.CallOption) (*SearchCompanyAndDepartmentResp, error)
	// ========== 部门相关接口 ==========
	// 创建部门
	CreateDepartment(ctx context.Context, in *CreateDepartmentReq, opts ...grpc.CallOption) (*CreateDepartmentResp, error)
	// 更新部门
	UpdateDepartment(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error)
	// 删除部门
	DeleteDepartment(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error)
	// 获取单个部门
	GetDepartment(ctx context.Context, in *GetDepartmentReq, opts ...grpc.CallOption) (*GetDepartmentResp, error)
	// 批量获取部门
	GetDepartments(ctx context.Context, in *GetDepartmentsReq, opts ...grpc.CallOption) (*GetDepartmentsResp, error)
	// 搜索部门
	SearchDepartment(ctx context.Context, in *SearchDepartmentReq, opts ...grpc.CallOption) (*SearchDepartmentResp, error)
	// 根据企业ID和部门ID获取所有人员（部门ID为空时返回企业的所有人员）（前台用）
	GetMembersByCompanyAndDepartment(ctx context.Context, in *GetMembersByCompanyAndDepartmentReq, opts ...grpc.CallOption) (*GetMembersByCompanyAndDepartmentResp, error)
	// 后台管理：根据企业ID和部门ID获取所有人员（包含更多字段和搜索条件）
	GetAdminMembersByCompanyAndDepartment(ctx context.Context, in *GetAdminMembersByCompanyAndDepartmentReq, opts ...grpc.CallOption) (*GetAdminMembersByCompanyAndDepartmentResp, error)
	// ========== 职位相关接口 ==========
	// 创建职位
	CreateJobTitle(ctx context.Context, in *CreateJobTitleReq, opts ...grpc.CallOption) (*CreateJobTitleResp, error)
	// 更新职位
	UpdateJobTitle(ctx context.Context, in *UpdateJobTitleReq, opts ...grpc.CallOption) (*UpdateJobTitleResp, error)
	// 删除职位
	DeleteJobTitle(ctx context.Context, in *DeleteJobTitleReq, opts ...grpc.CallOption) (*DeleteJobTitleResp, error)
	// 获取单个职位
	GetJobTitle(ctx context.Context, in *GetJobTitleReq, opts ...grpc.CallOption) (*GetJobTitleResp, error)
	// 批量获取职位
	GetJobTitles(ctx context.Context, in *GetJobTitlesReq, opts ...grpc.CallOption) (*GetJobTitlesResp, error)
	// 搜索职位
	SearchJobTitle(ctx context.Context, in *SearchJobTitleReq, opts ...grpc.CallOption) (*SearchJobTitleResp, error)
	// 根据部门获取职位
	GetJobTitlesByDepartment(ctx context.Context, in *GetJobTitlesByDepartmentReq, opts ...grpc.CallOption) (*GetJobTitlesByDepartmentResp, error)
	// ========== Job 表相关接口（从 job_title 同步） ==========
	// 创建职位
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobResp, error)
	// 更新职位
	UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobResp, error)
	// 删除职位
	DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobResp, error)
	// 获取单个职位
	GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*GetJobResp, error)
	// 批量获取职位
	GetJobs(ctx context.Context, in *GetJobsReq, opts ...grpc.CallOption) (*GetJobsResp, error)
	// 搜索职位
	SearchJob(ctx context.Context, in *SearchJobReq, opts ...grpc.CallOption) (*SearchJobResp, error)
	// 从 job_title 同步到 job 表
	SyncJobFromJobTitle(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// ========== 同步外部 OA 数据接口 ==========
	// 同步外部 OA 数据到 Chat 系统（通用方法，支持所有类型）
	SyncOADataToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// 同步外部 OA 部门数据到 Chat 系统
	SyncOADepartmentToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// 同步外部 OA 职位数据到 Chat 系统
	SyncOAJobTitleToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// 同步外部 OA 公司数据到 Chat 系统
	SyncOACompanyToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// 同步OA 岗位数据到 Chat 系统
	SyncJobToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
	// 同步外部 OA 用户数据到 Chat 系统
	SyncOAUserToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error)
}

type oaClient struct {
	cc grpc.ClientConnInterface
}

func NewOaClient(cc grpc.ClientConnInterface) OaClient {
	return &oaClient{cc}
}

func (c *oaClient) CreateCompany(ctx context.Context, in *CreateCompanyReq, opts ...grpc.CallOption) (*CreateCompanyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCompanyResp)
	err := c.cc.Invoke(ctx, Oa_CreateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) UpdateCompany(ctx context.Context, in *UpdateCompanyReq, opts ...grpc.CallOption) (*UpdateCompanyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCompanyResp)
	err := c.cc.Invoke(ctx, Oa_UpdateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) DeleteCompany(ctx context.Context, in *DeleteCompanyReq, opts ...grpc.CallOption) (*DeleteCompanyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCompanyResp)
	err := c.cc.Invoke(ctx, Oa_DeleteCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetCompany(ctx context.Context, in *GetCompanyReq, opts ...grpc.CallOption) (*GetCompanyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanyResp)
	err := c.cc.Invoke(ctx, Oa_GetCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetCompanies(ctx context.Context, in *GetCompaniesReq, opts ...grpc.CallOption) (*GetCompaniesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompaniesResp)
	err := c.cc.Invoke(ctx, Oa_GetCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SearchCompany(ctx context.Context, in *SearchCompanyReq, opts ...grpc.CallOption) (*SearchCompanyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCompanyResp)
	err := c.cc.Invoke(ctx, Oa_SearchCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetUserJoinedCompanies(ctx context.Context, in *GetUserJoinedCompaniesReq, opts ...grpc.CallOption) (*GetUserJoinedCompaniesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserJoinedCompaniesResp)
	err := c.cc.Invoke(ctx, Oa_GetUserJoinedCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetMyJoinedCompanies(ctx context.Context, in *GetMyJoinedCompaniesReq, opts ...grpc.CallOption) (*GetMyJoinedCompaniesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyJoinedCompaniesResp)
	err := c.cc.Invoke(ctx, Oa_GetMyJoinedCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetDepartmentTree(ctx context.Context, in *GetDepartmentTreeReq, opts ...grpc.CallOption) (*GetDepartmentTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentTreeResp)
	err := c.cc.Invoke(ctx, Oa_GetDepartmentTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SearchCompanyAndDepartment(ctx context.Context, in *SearchCompanyAndDepartmentReq, opts ...grpc.CallOption) (*SearchCompanyAndDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCompanyAndDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_SearchCompanyAndDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) CreateDepartment(ctx context.Context, in *CreateDepartmentReq, opts ...grpc.CallOption) (*CreateDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_CreateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) UpdateDepartment(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_UpdateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) DeleteDepartment(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_DeleteDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetDepartment(ctx context.Context, in *GetDepartmentReq, opts ...grpc.CallOption) (*GetDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_GetDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetDepartments(ctx context.Context, in *GetDepartmentsReq, opts ...grpc.CallOption) (*GetDepartmentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentsResp)
	err := c.cc.Invoke(ctx, Oa_GetDepartments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SearchDepartment(ctx context.Context, in *SearchDepartmentReq, opts ...grpc.CallOption) (*SearchDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_SearchDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetMembersByCompanyAndDepartment(ctx context.Context, in *GetMembersByCompanyAndDepartmentReq, opts ...grpc.CallOption) (*GetMembersByCompanyAndDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembersByCompanyAndDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_GetMembersByCompanyAndDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetAdminMembersByCompanyAndDepartment(ctx context.Context, in *GetAdminMembersByCompanyAndDepartmentReq, opts ...grpc.CallOption) (*GetAdminMembersByCompanyAndDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminMembersByCompanyAndDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_GetAdminMembersByCompanyAndDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) CreateJobTitle(ctx context.Context, in *CreateJobTitleReq, opts ...grpc.CallOption) (*CreateJobTitleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobTitleResp)
	err := c.cc.Invoke(ctx, Oa_CreateJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) UpdateJobTitle(ctx context.Context, in *UpdateJobTitleReq, opts ...grpc.CallOption) (*UpdateJobTitleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobTitleResp)
	err := c.cc.Invoke(ctx, Oa_UpdateJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) DeleteJobTitle(ctx context.Context, in *DeleteJobTitleReq, opts ...grpc.CallOption) (*DeleteJobTitleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobTitleResp)
	err := c.cc.Invoke(ctx, Oa_DeleteJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetJobTitle(ctx context.Context, in *GetJobTitleReq, opts ...grpc.CallOption) (*GetJobTitleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobTitleResp)
	err := c.cc.Invoke(ctx, Oa_GetJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetJobTitles(ctx context.Context, in *GetJobTitlesReq, opts ...grpc.CallOption) (*GetJobTitlesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobTitlesResp)
	err := c.cc.Invoke(ctx, Oa_GetJobTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SearchJobTitle(ctx context.Context, in *SearchJobTitleReq, opts ...grpc.CallOption) (*SearchJobTitleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchJobTitleResp)
	err := c.cc.Invoke(ctx, Oa_SearchJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetJobTitlesByDepartment(ctx context.Context, in *GetJobTitlesByDepartmentReq, opts ...grpc.CallOption) (*GetJobTitlesByDepartmentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobTitlesByDepartmentResp)
	err := c.cc.Invoke(ctx, Oa_GetJobTitlesByDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResp)
	err := c.cc.Invoke(ctx, Oa_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobResp)
	err := c.cc.Invoke(ctx, Oa_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobResp)
	err := c.cc.Invoke(ctx, Oa_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*GetJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResp)
	err := c.cc.Invoke(ctx, Oa_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) GetJobs(ctx context.Context, in *GetJobsReq, opts ...grpc.CallOption) (*GetJobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobsResp)
	err := c.cc.Invoke(ctx, Oa_GetJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SearchJob(ctx context.Context, in *SearchJobReq, opts ...grpc.CallOption) (*SearchJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchJobResp)
	err := c.cc.Invoke(ctx, Oa_SearchJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncJobFromJobTitle(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncJobFromJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncOADataToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncOADataToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncOADepartmentToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncOADepartmentToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncOAJobTitleToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncOAJobTitleToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncOACompanyToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncOACompanyToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncJobToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncJobToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oaClient) SyncOAUserToChat(ctx context.Context, in *SyncOADataToChatReq, opts ...grpc.CallOption) (*SyncOADataToChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOADataToChatResp)
	err := c.cc.Invoke(ctx, Oa_SyncOAUserToChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OaServer is the server API for Oa service.
// All implementations must embed UnimplementedOaServer
// for forward compatibility.
//
// OA RPC 服务（包含公司、部门、职位管理）
type OaServer interface {
	// ========== 公司相关接口 ==========
	// 创建公司
	CreateCompany(context.Context, *CreateCompanyReq) (*CreateCompanyResp, error)
	// 更新公司
	UpdateCompany(context.Context, *UpdateCompanyReq) (*UpdateCompanyResp, error)
	// 删除公司
	DeleteCompany(context.Context, *DeleteCompanyReq) (*DeleteCompanyResp, error)
	// 获取单个公司
	GetCompany(context.Context, *GetCompanyReq) (*GetCompanyResp, error)
	// 批量获取公司
	GetCompanies(context.Context, *GetCompaniesReq) (*GetCompaniesResp, error)
	// 搜索公司
	SearchCompany(context.Context, *SearchCompanyReq) (*SearchCompanyResp, error)
	// 获取用户加入的企业（不包含部门信息，部门通过 GetDepartmentTree 获取）
	GetUserJoinedCompanies(context.Context, *GetUserJoinedCompaniesReq) (*GetUserJoinedCompaniesResp, error)
	// 获取我加入的企业（只返回企业基本信息，不含部门，从上下文获取当前用户）
	GetMyJoinedCompanies(context.Context, *GetMyJoinedCompaniesReq) (*GetMyJoinedCompaniesResp, error)
	// 获取部门树（统一接口：如果department_id为空，返回企业的根部门列表；否则返回该部门的子部门列表）
	GetDepartmentTree(context.Context, *GetDepartmentTreeReq) (*GetDepartmentTreeResp, error)
	// 搜索企业和部门（返回树形结构）
	SearchCompanyAndDepartment(context.Context, *SearchCompanyAndDepartmentReq) (*SearchCompanyAndDepartmentResp, error)
	// ========== 部门相关接口 ==========
	// 创建部门
	CreateDepartment(context.Context, *CreateDepartmentReq) (*CreateDepartmentResp, error)
	// 更新部门
	UpdateDepartment(context.Context, *UpdateDepartmentReq) (*UpdateDepartmentResp, error)
	// 删除部门
	DeleteDepartment(context.Context, *DeleteDepartmentReq) (*DeleteDepartmentResp, error)
	// 获取单个部门
	GetDepartment(context.Context, *GetDepartmentReq) (*GetDepartmentResp, error)
	// 批量获取部门
	GetDepartments(context.Context, *GetDepartmentsReq) (*GetDepartmentsResp, error)
	// 搜索部门
	SearchDepartment(context.Context, *SearchDepartmentReq) (*SearchDepartmentResp, error)
	// 根据企业ID和部门ID获取所有人员（部门ID为空时返回企业的所有人员）（前台用）
	GetMembersByCompanyAndDepartment(context.Context, *GetMembersByCompanyAndDepartmentReq) (*GetMembersByCompanyAndDepartmentResp, error)
	// 后台管理：根据企业ID和部门ID获取所有人员（包含更多字段和搜索条件）
	GetAdminMembersByCompanyAndDepartment(context.Context, *GetAdminMembersByCompanyAndDepartmentReq) (*GetAdminMembersByCompanyAndDepartmentResp, error)
	// ========== 职位相关接口 ==========
	// 创建职位
	CreateJobTitle(context.Context, *CreateJobTitleReq) (*CreateJobTitleResp, error)
	// 更新职位
	UpdateJobTitle(context.Context, *UpdateJobTitleReq) (*UpdateJobTitleResp, error)
	// 删除职位
	DeleteJobTitle(context.Context, *DeleteJobTitleReq) (*DeleteJobTitleResp, error)
	// 获取单个职位
	GetJobTitle(context.Context, *GetJobTitleReq) (*GetJobTitleResp, error)
	// 批量获取职位
	GetJobTitles(context.Context, *GetJobTitlesReq) (*GetJobTitlesResp, error)
	// 搜索职位
	SearchJobTitle(context.Context, *SearchJobTitleReq) (*SearchJobTitleResp, error)
	// 根据部门获取职位
	GetJobTitlesByDepartment(context.Context, *GetJobTitlesByDepartmentReq) (*GetJobTitlesByDepartmentResp, error)
	// ========== Job 表相关接口（从 job_title 同步） ==========
	// 创建职位
	CreateJob(context.Context, *CreateJobReq) (*CreateJobResp, error)
	// 更新职位
	UpdateJob(context.Context, *UpdateJobReq) (*UpdateJobResp, error)
	// 删除职位
	DeleteJob(context.Context, *DeleteJobReq) (*DeleteJobResp, error)
	// 获取单个职位
	GetJob(context.Context, *GetJobReq) (*GetJobResp, error)
	// 批量获取职位
	GetJobs(context.Context, *GetJobsReq) (*GetJobsResp, error)
	// 搜索职位
	SearchJob(context.Context, *SearchJobReq) (*SearchJobResp, error)
	// 从 job_title 同步到 job 表
	SyncJobFromJobTitle(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// ========== 同步外部 OA 数据接口 ==========
	// 同步外部 OA 数据到 Chat 系统（通用方法，支持所有类型）
	SyncOADataToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// 同步外部 OA 部门数据到 Chat 系统
	SyncOADepartmentToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// 同步外部 OA 职位数据到 Chat 系统
	SyncOAJobTitleToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// 同步外部 OA 公司数据到 Chat 系统
	SyncOACompanyToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// 同步OA 岗位数据到 Chat 系统
	SyncJobToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	// 同步外部 OA 用户数据到 Chat 系统
	SyncOAUserToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error)
	mustEmbedUnimplementedOaServer()
}

// UnimplementedOaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOaServer struct{}

func (UnimplementedOaServer) CreateCompany(context.Context, *CreateCompanyReq) (*CreateCompanyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}
func (UnimplementedOaServer) UpdateCompany(context.Context, *UpdateCompanyReq) (*UpdateCompanyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (UnimplementedOaServer) DeleteCompany(context.Context, *DeleteCompanyReq) (*DeleteCompanyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompany not implemented")
}
func (UnimplementedOaServer) GetCompany(context.Context, *GetCompanyReq) (*GetCompanyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (UnimplementedOaServer) GetCompanies(context.Context, *GetCompaniesReq) (*GetCompaniesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanies not implemented")
}
func (UnimplementedOaServer) SearchCompany(context.Context, *SearchCompanyReq) (*SearchCompanyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCompany not implemented")
}
func (UnimplementedOaServer) GetUserJoinedCompanies(context.Context, *GetUserJoinedCompaniesReq) (*GetUserJoinedCompaniesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserJoinedCompanies not implemented")
}
func (UnimplementedOaServer) GetMyJoinedCompanies(context.Context, *GetMyJoinedCompaniesReq) (*GetMyJoinedCompaniesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyJoinedCompanies not implemented")
}
func (UnimplementedOaServer) GetDepartmentTree(context.Context, *GetDepartmentTreeReq) (*GetDepartmentTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentTree not implemented")
}
func (UnimplementedOaServer) SearchCompanyAndDepartment(context.Context, *SearchCompanyAndDepartmentReq) (*SearchCompanyAndDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCompanyAndDepartment not implemented")
}
func (UnimplementedOaServer) CreateDepartment(context.Context, *CreateDepartmentReq) (*CreateDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDepartment not implemented")
}
func (UnimplementedOaServer) UpdateDepartment(context.Context, *UpdateDepartmentReq) (*UpdateDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartment not implemented")
}
func (UnimplementedOaServer) DeleteDepartment(context.Context, *DeleteDepartmentReq) (*DeleteDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedOaServer) GetDepartment(context.Context, *GetDepartmentReq) (*GetDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartment not implemented")
}
func (UnimplementedOaServer) GetDepartments(context.Context, *GetDepartmentsReq) (*GetDepartmentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartments not implemented")
}
func (UnimplementedOaServer) SearchDepartment(context.Context, *SearchDepartmentReq) (*SearchDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDepartment not implemented")
}
func (UnimplementedOaServer) GetMembersByCompanyAndDepartment(context.Context, *GetMembersByCompanyAndDepartmentReq) (*GetMembersByCompanyAndDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembersByCompanyAndDepartment not implemented")
}
func (UnimplementedOaServer) GetAdminMembersByCompanyAndDepartment(context.Context, *GetAdminMembersByCompanyAndDepartmentReq) (*GetAdminMembersByCompanyAndDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminMembersByCompanyAndDepartment not implemented")
}
func (UnimplementedOaServer) CreateJobTitle(context.Context, *CreateJobTitleReq) (*CreateJobTitleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobTitle not implemented")
}
func (UnimplementedOaServer) UpdateJobTitle(context.Context, *UpdateJobTitleReq) (*UpdateJobTitleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobTitle not implemented")
}
func (UnimplementedOaServer) DeleteJobTitle(context.Context, *DeleteJobTitleReq) (*DeleteJobTitleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobTitle not implemented")
}
func (UnimplementedOaServer) GetJobTitle(context.Context, *GetJobTitleReq) (*GetJobTitleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobTitle not implemented")
}
func (UnimplementedOaServer) GetJobTitles(context.Context, *GetJobTitlesReq) (*GetJobTitlesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobTitles not implemented")
}
func (UnimplementedOaServer) SearchJobTitle(context.Context, *SearchJobTitleReq) (*SearchJobTitleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchJobTitle not implemented")
}
func (UnimplementedOaServer) GetJobTitlesByDepartment(context.Context, *GetJobTitlesByDepartmentReq) (*GetJobTitlesByDepartmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobTitlesByDepartment not implemented")
}
func (UnimplementedOaServer) CreateJob(context.Context, *CreateJobReq) (*CreateJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedOaServer) UpdateJob(context.Context, *UpdateJobReq) (*UpdateJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedOaServer) DeleteJob(context.Context, *DeleteJobReq) (*DeleteJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedOaServer) GetJob(context.Context, *GetJobReq) (*GetJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedOaServer) GetJobs(context.Context, *GetJobsReq) (*GetJobsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedOaServer) SearchJob(context.Context, *SearchJobReq) (*SearchJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchJob not implemented")
}
func (UnimplementedOaServer) SyncJobFromJobTitle(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncJobFromJobTitle not implemented")
}
func (UnimplementedOaServer) SyncOADataToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOADataToChat not implemented")
}
func (UnimplementedOaServer) SyncOADepartmentToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOADepartmentToChat not implemented")
}
func (UnimplementedOaServer) SyncOAJobTitleToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOAJobTitleToChat not implemented")
}
func (UnimplementedOaServer) SyncOACompanyToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOACompanyToChat not implemented")
}
func (UnimplementedOaServer) SyncJobToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncJobToChat not implemented")
}
func (UnimplementedOaServer) SyncOAUserToChat(context.Context, *SyncOADataToChatReq) (*SyncOADataToChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOAUserToChat not implemented")
}
func (UnimplementedOaServer) mustEmbedUnimplementedOaServer() {}
func (UnimplementedOaServer) testEmbeddedByValue()            {}

// UnsafeOaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OaServer will
// result in compilation errors.
type UnsafeOaServer interface {
	mustEmbedUnimplementedOaServer()
}

func RegisterOaServer(s grpc.ServiceRegistrar, srv OaServer) {
	// If the following call pancis, it indicates UnimplementedOaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Oa_ServiceDesc, srv)
}

func _Oa_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_CreateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).CreateCompany(ctx, req.(*CreateCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_UpdateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).UpdateCompany(ctx, req.(*UpdateCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_DeleteCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).DeleteCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_DeleteCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).DeleteCompany(ctx, req.(*DeleteCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetCompany(ctx, req.(*GetCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompaniesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetCompanies(ctx, req.(*GetCompaniesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SearchCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SearchCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SearchCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SearchCompany(ctx, req.(*SearchCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetUserJoinedCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserJoinedCompaniesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetUserJoinedCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetUserJoinedCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetUserJoinedCompanies(ctx, req.(*GetUserJoinedCompaniesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetMyJoinedCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyJoinedCompaniesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetMyJoinedCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetMyJoinedCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetMyJoinedCompanies(ctx, req.(*GetMyJoinedCompaniesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetDepartmentTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetDepartmentTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetDepartmentTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetDepartmentTree(ctx, req.(*GetDepartmentTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SearchCompanyAndDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCompanyAndDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SearchCompanyAndDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SearchCompanyAndDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SearchCompanyAndDepartment(ctx, req.(*SearchCompanyAndDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_CreateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).CreateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_CreateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).CreateDepartment(ctx, req.(*CreateDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_UpdateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).UpdateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_UpdateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).UpdateDepartment(ctx, req.(*UpdateDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_DeleteDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).DeleteDepartment(ctx, req.(*DeleteDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetDepartment(ctx, req.(*GetDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetDepartments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetDepartments(ctx, req.(*GetDepartmentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SearchDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SearchDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SearchDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SearchDepartment(ctx, req.(*SearchDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetMembersByCompanyAndDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersByCompanyAndDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetMembersByCompanyAndDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetMembersByCompanyAndDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetMembersByCompanyAndDepartment(ctx, req.(*GetMembersByCompanyAndDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetAdminMembersByCompanyAndDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminMembersByCompanyAndDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetAdminMembersByCompanyAndDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetAdminMembersByCompanyAndDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetAdminMembersByCompanyAndDepartment(ctx, req.(*GetAdminMembersByCompanyAndDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_CreateJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobTitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).CreateJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_CreateJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).CreateJobTitle(ctx, req.(*CreateJobTitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_UpdateJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobTitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).UpdateJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_UpdateJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).UpdateJobTitle(ctx, req.(*UpdateJobTitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_DeleteJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobTitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).DeleteJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_DeleteJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).DeleteJobTitle(ctx, req.(*DeleteJobTitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobTitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetJobTitle(ctx, req.(*GetJobTitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetJobTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobTitlesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetJobTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetJobTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetJobTitles(ctx, req.(*GetJobTitlesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SearchJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobTitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SearchJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SearchJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SearchJobTitle(ctx, req.(*SearchJobTitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetJobTitlesByDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobTitlesByDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetJobTitlesByDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetJobTitlesByDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetJobTitlesByDepartment(ctx, req.(*GetJobTitlesByDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).UpdateJob(ctx, req.(*UpdateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).DeleteJob(ctx, req.(*DeleteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetJob(ctx, req.(*GetJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_GetJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).GetJobs(ctx, req.(*GetJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SearchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SearchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SearchJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SearchJob(ctx, req.(*SearchJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncJobFromJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncJobFromJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncJobFromJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncJobFromJobTitle(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncOADataToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncOADataToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncOADataToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncOADataToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncOADepartmentToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncOADepartmentToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncOADepartmentToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncOADepartmentToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncOAJobTitleToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncOAJobTitleToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncOAJobTitleToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncOAJobTitleToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncOACompanyToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncOACompanyToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncOACompanyToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncOACompanyToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncJobToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncJobToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncJobToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncJobToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oa_SyncOAUserToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOADataToChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OaServer).SyncOAUserToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oa_SyncOAUserToChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OaServer).SyncOAUserToChat(ctx, req.(*SyncOADataToChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Oa_ServiceDesc is the grpc.ServiceDesc for Oa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.oa.oa",
	HandlerType: (*OaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompany",
			Handler:    _Oa_CreateCompany_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _Oa_UpdateCompany_Handler,
		},
		{
			MethodName: "DeleteCompany",
			Handler:    _Oa_DeleteCompany_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _Oa_GetCompany_Handler,
		},
		{
			MethodName: "GetCompanies",
			Handler:    _Oa_GetCompanies_Handler,
		},
		{
			MethodName: "SearchCompany",
			Handler:    _Oa_SearchCompany_Handler,
		},
		{
			MethodName: "GetUserJoinedCompanies",
			Handler:    _Oa_GetUserJoinedCompanies_Handler,
		},
		{
			MethodName: "GetMyJoinedCompanies",
			Handler:    _Oa_GetMyJoinedCompanies_Handler,
		},
		{
			MethodName: "GetDepartmentTree",
			Handler:    _Oa_GetDepartmentTree_Handler,
		},
		{
			MethodName: "SearchCompanyAndDepartment",
			Handler:    _Oa_SearchCompanyAndDepartment_Handler,
		},
		{
			MethodName: "CreateDepartment",
			Handler:    _Oa_CreateDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartment",
			Handler:    _Oa_UpdateDepartment_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _Oa_DeleteDepartment_Handler,
		},
		{
			MethodName: "GetDepartment",
			Handler:    _Oa_GetDepartment_Handler,
		},
		{
			MethodName: "GetDepartments",
			Handler:    _Oa_GetDepartments_Handler,
		},
		{
			MethodName: "SearchDepartment",
			Handler:    _Oa_SearchDepartment_Handler,
		},
		{
			MethodName: "GetMembersByCompanyAndDepartment",
			Handler:    _Oa_GetMembersByCompanyAndDepartment_Handler,
		},
		{
			MethodName: "GetAdminMembersByCompanyAndDepartment",
			Handler:    _Oa_GetAdminMembersByCompanyAndDepartment_Handler,
		},
		{
			MethodName: "CreateJobTitle",
			Handler:    _Oa_CreateJobTitle_Handler,
		},
		{
			MethodName: "UpdateJobTitle",
			Handler:    _Oa_UpdateJobTitle_Handler,
		},
		{
			MethodName: "DeleteJobTitle",
			Handler:    _Oa_DeleteJobTitle_Handler,
		},
		{
			MethodName: "GetJobTitle",
			Handler:    _Oa_GetJobTitle_Handler,
		},
		{
			MethodName: "GetJobTitles",
			Handler:    _Oa_GetJobTitles_Handler,
		},
		{
			MethodName: "SearchJobTitle",
			Handler:    _Oa_SearchJobTitle_Handler,
		},
		{
			MethodName: "GetJobTitlesByDepartment",
			Handler:    _Oa_GetJobTitlesByDepartment_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Oa_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _Oa_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _Oa_DeleteJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Oa_GetJob_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _Oa_GetJobs_Handler,
		},
		{
			MethodName: "SearchJob",
			Handler:    _Oa_SearchJob_Handler,
		},
		{
			MethodName: "SyncJobFromJobTitle",
			Handler:    _Oa_SyncJobFromJobTitle_Handler,
		},
		{
			MethodName: "SyncOADataToChat",
			Handler:    _Oa_SyncOADataToChat_Handler,
		},
		{
			MethodName: "SyncOADepartmentToChat",
			Handler:    _Oa_SyncOADepartmentToChat_Handler,
		},
		{
			MethodName: "SyncOAJobTitleToChat",
			Handler:    _Oa_SyncOAJobTitleToChat_Handler,
		},
		{
			MethodName: "SyncOACompanyToChat",
			Handler:    _Oa_SyncOACompanyToChat_Handler,
		},
		{
			MethodName: "SyncJobToChat",
			Handler:    _Oa_SyncJobToChat_Handler,
		},
		{
			MethodName: "SyncOAUserToChat",
			Handler:    _Oa_SyncOAUserToChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oa/oa.proto",
}
