// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: call/call.proto

package call

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallService_CreateCall_FullMethodName                  = "/openim.call.CallService/CreateCall"
	CallService_RespondCallInvitation_FullMethodName       = "/openim.call.CallService/RespondCallInvitation"
	CallService_CancelCallInvitation_FullMethodName        = "/openim.call.CallService/CancelCallInvitation"
	CallService_EndCall_FullMethodName                     = "/openim.call.CallService/EndCall"
	CallService_GetCallToken_FullMethodName                = "/openim.call.CallService/GetCallToken"
	CallService_GetMyPendingCallInvitations_FullMethodName = "/openim.call.CallService/GetMyPendingCallInvitations"
)

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallServiceClient interface {
	// 发起1v1通话
	CreateCall(ctx context.Context, in *CreateCallReq, opts ...grpc.CallOption) (*CreateCallResp, error)
	// 响应通话邀请（接听/拒绝）
	RespondCallInvitation(ctx context.Context, in *RespondCallInvitationReq, opts ...grpc.CallOption) (*RespondCallInvitationResp, error)
	// 取消通话邀请（主叫方取消）
	CancelCallInvitation(ctx context.Context, in *CancelCallInvitationReq, opts ...grpc.CallOption) (*CancelCallInvitationResp, error)
	// 结束通话
	EndCall(ctx context.Context, in *EndCallReq, opts ...grpc.CallOption) (*EndCallResp, error)
	// 获取通话 Token（断线重连）
	GetCallToken(ctx context.Context, in *GetCallTokenReq, opts ...grpc.CallOption) (*GetCallTokenResp, error)
	// 获取我的待处理来电列表
	GetMyPendingCallInvitations(ctx context.Context, in *GetMyPendingCallInvitationsReq, opts ...grpc.CallOption) (*GetMyPendingCallInvitationsResp, error)
}

type callServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallServiceClient(cc grpc.ClientConnInterface) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) CreateCall(ctx context.Context, in *CreateCallReq, opts ...grpc.CallOption) (*CreateCallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCallResp)
	err := c.cc.Invoke(ctx, CallService_CreateCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) RespondCallInvitation(ctx context.Context, in *RespondCallInvitationReq, opts ...grpc.CallOption) (*RespondCallInvitationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondCallInvitationResp)
	err := c.cc.Invoke(ctx, CallService_RespondCallInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) CancelCallInvitation(ctx context.Context, in *CancelCallInvitationReq, opts ...grpc.CallOption) (*CancelCallInvitationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCallInvitationResp)
	err := c.cc.Invoke(ctx, CallService_CancelCallInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) EndCall(ctx context.Context, in *EndCallReq, opts ...grpc.CallOption) (*EndCallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndCallResp)
	err := c.cc.Invoke(ctx, CallService_EndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) GetCallToken(ctx context.Context, in *GetCallTokenReq, opts ...grpc.CallOption) (*GetCallTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCallTokenResp)
	err := c.cc.Invoke(ctx, CallService_GetCallToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) GetMyPendingCallInvitations(ctx context.Context, in *GetMyPendingCallInvitationsReq, opts ...grpc.CallOption) (*GetMyPendingCallInvitationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyPendingCallInvitationsResp)
	err := c.cc.Invoke(ctx, CallService_GetMyPendingCallInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
// All implementations must embed UnimplementedCallServiceServer
// for forward compatibility.
type CallServiceServer interface {
	// 发起1v1通话
	CreateCall(context.Context, *CreateCallReq) (*CreateCallResp, error)
	// 响应通话邀请（接听/拒绝）
	RespondCallInvitation(context.Context, *RespondCallInvitationReq) (*RespondCallInvitationResp, error)
	// 取消通话邀请（主叫方取消）
	CancelCallInvitation(context.Context, *CancelCallInvitationReq) (*CancelCallInvitationResp, error)
	// 结束通话
	EndCall(context.Context, *EndCallReq) (*EndCallResp, error)
	// 获取通话 Token（断线重连）
	GetCallToken(context.Context, *GetCallTokenReq) (*GetCallTokenResp, error)
	// 获取我的待处理来电列表
	GetMyPendingCallInvitations(context.Context, *GetMyPendingCallInvitationsReq) (*GetMyPendingCallInvitationsResp, error)
	mustEmbedUnimplementedCallServiceServer()
}

// UnimplementedCallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallServiceServer struct{}

func (UnimplementedCallServiceServer) CreateCall(context.Context, *CreateCallReq) (*CreateCallResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCall not implemented")
}
func (UnimplementedCallServiceServer) RespondCallInvitation(context.Context, *RespondCallInvitationReq) (*RespondCallInvitationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondCallInvitation not implemented")
}
func (UnimplementedCallServiceServer) CancelCallInvitation(context.Context, *CancelCallInvitationReq) (*CancelCallInvitationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelCallInvitation not implemented")
}
func (UnimplementedCallServiceServer) EndCall(context.Context, *EndCallReq) (*EndCallResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EndCall not implemented")
}
func (UnimplementedCallServiceServer) GetCallToken(context.Context, *GetCallTokenReq) (*GetCallTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCallToken not implemented")
}
func (UnimplementedCallServiceServer) GetMyPendingCallInvitations(context.Context, *GetMyPendingCallInvitationsReq) (*GetMyPendingCallInvitationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyPendingCallInvitations not implemented")
}
func (UnimplementedCallServiceServer) mustEmbedUnimplementedCallServiceServer() {}
func (UnimplementedCallServiceServer) testEmbeddedByValue()                     {}

// UnsafeCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServiceServer will
// result in compilation errors.
type UnsafeCallServiceServer interface {
	mustEmbedUnimplementedCallServiceServer()
}

func RegisterCallServiceServer(s grpc.ServiceRegistrar, srv CallServiceServer) {
	// If the following call panics, it indicates UnimplementedCallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallService_ServiceDesc, srv)
}

func _CallService_CreateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CreateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_CreateCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CreateCall(ctx, req.(*CreateCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_RespondCallInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondCallInvitationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).RespondCallInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_RespondCallInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).RespondCallInvitation(ctx, req.(*RespondCallInvitationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_CancelCallInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallInvitationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CancelCallInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_CancelCallInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CancelCallInvitation(ctx, req.(*CancelCallInvitationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_EndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).EndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_EndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).EndCall(ctx, req.(*EndCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_GetCallToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).GetCallToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_GetCallToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).GetCallToken(ctx, req.(*GetCallTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_GetMyPendingCallInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyPendingCallInvitationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).GetMyPendingCallInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_GetMyPendingCallInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).GetMyPendingCallInvitations(ctx, req.(*GetMyPendingCallInvitationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CallService_ServiceDesc is the grpc.ServiceDesc for CallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.call.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCall",
			Handler:    _CallService_CreateCall_Handler,
		},
		{
			MethodName: "RespondCallInvitation",
			Handler:    _CallService_RespondCallInvitation_Handler,
		},
		{
			MethodName: "CancelCallInvitation",
			Handler:    _CallService_CancelCallInvitation_Handler,
		},
		{
			MethodName: "EndCall",
			Handler:    _CallService_EndCall_Handler,
		},
		{
			MethodName: "GetCallToken",
			Handler:    _CallService_GetCallToken_Handler,
		},
		{
			MethodName: "GetMyPendingCallInvitations",
			Handler:    _CallService_GetMyPendingCallInvitations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "call/call.proto",
}
