// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: call/call.proto

package call

import (
	livekit_meeting "github.com/openimsdk/protocol/livekit_meeting"
	sdkws "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallInfo 通话记录信息
type CallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"` // "voice" 或 "video"
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status"`     // ringing/ongoing/ended/rejected/cancelled/timeout/busy
	RoomID        string                 `protobuf:"bytes,6,opt,name=roomID,proto3" json:"roomID"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime"`
	AnswerTime    int64                  `protobuf:"varint,8,opt,name=answerTime,proto3" json:"answerTime"`
	EndTime       int64                  `protobuf:"varint,9,opt,name=endTime,proto3" json:"endTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallInfo) Reset() {
	*x = CallInfo{}
	mi := &file_call_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallInfo) ProtoMessage() {}

func (x *CallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallInfo.ProtoReflect.Descriptor instead.
func (*CallInfo) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{0}
}

func (x *CallInfo) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallInfo) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallInfo) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallInfo) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CallInfo) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *CallInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CallInfo) GetAnswerTime() int64 {
	if x != nil {
		return x.AnswerTime
	}
	return 0
}

func (x *CallInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// CreateCallReq 发起1v1通话请求
type CreateCallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CalleeUserID  string                 `protobuf:"bytes,1,opt,name=calleeUserID,proto3" json:"calleeUserID"`   // 被叫方用户ID
	CallType      string                 `protobuf:"bytes,2,opt,name=callType,proto3" json:"callType"`           // "voice" 或 "video"
	IdempotentKey string                 `protobuf:"bytes,3,opt,name=idempotentKey,proto3" json:"idempotentKey"` // 幂等键，防止重复创建
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCallReq) Reset() {
	*x = CreateCallReq{}
	mi := &file_call_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCallReq) ProtoMessage() {}

func (x *CreateCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCallReq.ProtoReflect.Descriptor instead.
func (*CreateCallReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCallReq) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CreateCallReq) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CreateCallReq) GetIdempotentKey() string {
	if x != nil {
		return x.IdempotentKey
	}
	return ""
}

// CreateCallResp 发起通话响应
type CreateCallResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	CallID        string                       `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	LiveKit       *livekit_meeting.LiveKitInfo `protobuf:"bytes,2,opt,name=liveKit,proto3" json:"liveKit"` // 主叫方的 LiveKit 连接信息
	RoomID        string                       `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCallResp) Reset() {
	*x = CreateCallResp{}
	mi := &file_call_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCallResp) ProtoMessage() {}

func (x *CreateCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCallResp.ProtoReflect.Descriptor instead.
func (*CreateCallResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCallResp) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CreateCallResp) GetLiveKit() *livekit_meeting.LiveKitInfo {
	if x != nil {
		return x.LiveKit
	}
	return nil
}

func (x *CreateCallResp) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

// RespondCallInvitationReq 响应通话邀请
type RespondCallInvitationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept"` // true=接听 false=拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondCallInvitationReq) Reset() {
	*x = RespondCallInvitationReq{}
	mi := &file_call_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondCallInvitationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondCallInvitationReq) ProtoMessage() {}

func (x *RespondCallInvitationReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondCallInvitationReq.ProtoReflect.Descriptor instead.
func (*RespondCallInvitationReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{3}
}

func (x *RespondCallInvitationReq) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *RespondCallInvitationReq) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// RespondCallInvitationResp 响应通话邀请结果
type RespondCallInvitationResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	LiveKit       *livekit_meeting.LiveKitInfo `protobuf:"bytes,1,opt,name=liveKit,proto3" json:"liveKit"` // 接听时返回 LiveKit 连接信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondCallInvitationResp) Reset() {
	*x = RespondCallInvitationResp{}
	mi := &file_call_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondCallInvitationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondCallInvitationResp) ProtoMessage() {}

func (x *RespondCallInvitationResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondCallInvitationResp.ProtoReflect.Descriptor instead.
func (*RespondCallInvitationResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{4}
}

func (x *RespondCallInvitationResp) GetLiveKit() *livekit_meeting.LiveKitInfo {
	if x != nil {
		return x.LiveKit
	}
	return nil
}

// CancelCallInvitationReq 取消通话邀请（主叫方取消）
type CancelCallInvitationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCallInvitationReq) Reset() {
	*x = CancelCallInvitationReq{}
	mi := &file_call_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCallInvitationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCallInvitationReq) ProtoMessage() {}

func (x *CancelCallInvitationReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCallInvitationReq.ProtoReflect.Descriptor instead.
func (*CancelCallInvitationReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{5}
}

func (x *CancelCallInvitationReq) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

// CancelCallInvitationResp 取消通话邀请结果
type CancelCallInvitationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCallInvitationResp) Reset() {
	*x = CancelCallInvitationResp{}
	mi := &file_call_call_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCallInvitationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCallInvitationResp) ProtoMessage() {}

func (x *CancelCallInvitationResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCallInvitationResp.ProtoReflect.Descriptor instead.
func (*CancelCallInvitationResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{6}
}

// EndCallReq 结束通话
type EndCallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallReq) Reset() {
	*x = EndCallReq{}
	mi := &file_call_call_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallReq) ProtoMessage() {}

func (x *EndCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallReq.ProtoReflect.Descriptor instead.
func (*EndCallReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{7}
}

func (x *EndCallReq) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

// EndCallResp 结束通话结果
type EndCallResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallResp) Reset() {
	*x = EndCallResp{}
	mi := &file_call_call_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResp) ProtoMessage() {}

func (x *EndCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResp.ProtoReflect.Descriptor instead.
func (*EndCallResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{8}
}

// GetCallTokenReq 获取通话 Token（断线重连用）
type GetCallTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallTokenReq) Reset() {
	*x = GetCallTokenReq{}
	mi := &file_call_call_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallTokenReq) ProtoMessage() {}

func (x *GetCallTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallTokenReq.ProtoReflect.Descriptor instead.
func (*GetCallTokenReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{9}
}

func (x *GetCallTokenReq) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

// GetCallTokenResp 获取通话 Token 结果
type GetCallTokenResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	LiveKit       *livekit_meeting.LiveKitInfo `protobuf:"bytes,1,opt,name=liveKit,proto3" json:"liveKit"`
	RoomID        string                       `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallTokenResp) Reset() {
	*x = GetCallTokenResp{}
	mi := &file_call_call_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallTokenResp) ProtoMessage() {}

func (x *GetCallTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallTokenResp.ProtoReflect.Descriptor instead.
func (*GetCallTokenResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{10}
}

func (x *GetCallTokenResp) GetLiveKit() *livekit_meeting.LiveKitInfo {
	if x != nil {
		return x.LiveKit
	}
	return nil
}

func (x *GetCallTokenResp) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

// GetMyPendingCallInvitationsReq 获取我的待处理来电
type GetMyPendingCallInvitationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPendingCallInvitationsReq) Reset() {
	*x = GetMyPendingCallInvitationsReq{}
	mi := &file_call_call_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPendingCallInvitationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPendingCallInvitationsReq) ProtoMessage() {}

func (x *GetMyPendingCallInvitationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPendingCallInvitationsReq.ProtoReflect.Descriptor instead.
func (*GetMyPendingCallInvitationsReq) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{11}
}

// GetMyPendingCallInvitationsResp 待处理来电列表
type GetMyPendingCallInvitationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*CallInvitationTips  `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPendingCallInvitationsResp) Reset() {
	*x = GetMyPendingCallInvitationsResp{}
	mi := &file_call_call_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPendingCallInvitationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPendingCallInvitationsResp) ProtoMessage() {}

func (x *GetMyPendingCallInvitationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPendingCallInvitationsResp.ProtoReflect.Descriptor instead.
func (*GetMyPendingCallInvitationsResp) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyPendingCallInvitationsResp) GetCalls() []*CallInvitationTips {
	if x != nil {
		return x.Calls
	}
	return nil
}

// CallInvitationTips 来电邀请通知
type CallInvitationTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"` // "voice" 或 "video"
	RoomID        string                 `protobuf:"bytes,5,opt,name=roomID,proto3" json:"roomID"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime"`
	CallerInfo    *sdkws.UserInfo        `protobuf:"bytes,7,opt,name=callerInfo,proto3" json:"callerInfo"` // 主叫方用户信息（昵称、头像）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallInvitationTips) Reset() {
	*x = CallInvitationTips{}
	mi := &file_call_call_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallInvitationTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallInvitationTips) ProtoMessage() {}

func (x *CallInvitationTips) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallInvitationTips.ProtoReflect.Descriptor instead.
func (*CallInvitationTips) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{13}
}

func (x *CallInvitationTips) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallInvitationTips) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallInvitationTips) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallInvitationTips) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallInvitationTips) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *CallInvitationTips) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CallInvitationTips) GetCallerInfo() *sdkws.UserInfo {
	if x != nil {
		return x.CallerInfo
	}
	return nil
}

// CallRespondedTips 通话响应通知（接听/拒绝）
type CallRespondedTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"`
	Accepted      bool                   `protobuf:"varint,5,opt,name=accepted,proto3" json:"accepted"`
	CalleeInfo    *sdkws.UserInfo        `protobuf:"bytes,6,opt,name=calleeInfo,proto3" json:"calleeInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRespondedTips) Reset() {
	*x = CallRespondedTips{}
	mi := &file_call_call_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRespondedTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRespondedTips) ProtoMessage() {}

func (x *CallRespondedTips) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRespondedTips.ProtoReflect.Descriptor instead.
func (*CallRespondedTips) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{14}
}

func (x *CallRespondedTips) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallRespondedTips) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallRespondedTips) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallRespondedTips) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallRespondedTips) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CallRespondedTips) GetCalleeInfo() *sdkws.UserInfo {
	if x != nil {
		return x.CalleeInfo
	}
	return nil
}

// CallCancelledTips 通话取消通知（主叫取消）
type CallCancelledTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"`
	CallerInfo    *sdkws.UserInfo        `protobuf:"bytes,5,opt,name=callerInfo,proto3" json:"callerInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCancelledTips) Reset() {
	*x = CallCancelledTips{}
	mi := &file_call_call_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCancelledTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCancelledTips) ProtoMessage() {}

func (x *CallCancelledTips) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCancelledTips.ProtoReflect.Descriptor instead.
func (*CallCancelledTips) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{15}
}

func (x *CallCancelledTips) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallCancelledTips) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallCancelledTips) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallCancelledTips) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallCancelledTips) GetCallerInfo() *sdkws.UserInfo {
	if x != nil {
		return x.CallerInfo
	}
	return nil
}

// CallEndedTips 通话结束通知
type CallEndedTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration"` // 通话时长（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEndedTips) Reset() {
	*x = CallEndedTips{}
	mi := &file_call_call_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEndedTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEndedTips) ProtoMessage() {}

func (x *CallEndedTips) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEndedTips.ProtoReflect.Descriptor instead.
func (*CallEndedTips) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{16}
}

func (x *CallEndedTips) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallEndedTips) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallEndedTips) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallEndedTips) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallEndedTips) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// CallTimeoutTips 通话超时通知（无人接听）
type CallTimeoutTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=callID,proto3" json:"callID"`
	CallerUserID  string                 `protobuf:"bytes,2,opt,name=callerUserID,proto3" json:"callerUserID"`
	CalleeUserID  string                 `protobuf:"bytes,3,opt,name=calleeUserID,proto3" json:"calleeUserID"`
	CallType      string                 `protobuf:"bytes,4,opt,name=callType,proto3" json:"callType"`
	CallerInfo    *sdkws.UserInfo        `protobuf:"bytes,5,opt,name=callerInfo,proto3" json:"callerInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTimeoutTips) Reset() {
	*x = CallTimeoutTips{}
	mi := &file_call_call_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTimeoutTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTimeoutTips) ProtoMessage() {}

func (x *CallTimeoutTips) ProtoReflect() protoreflect.Message {
	mi := &file_call_call_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTimeoutTips.ProtoReflect.Descriptor instead.
func (*CallTimeoutTips) Descriptor() ([]byte, []int) {
	return file_call_call_proto_rawDescGZIP(), []int{17}
}

func (x *CallTimeoutTips) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallTimeoutTips) GetCallerUserID() string {
	if x != nil {
		return x.CallerUserID
	}
	return ""
}

func (x *CallTimeoutTips) GetCalleeUserID() string {
	if x != nil {
		return x.CalleeUserID
	}
	return ""
}

func (x *CallTimeoutTips) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallTimeoutTips) GetCallerInfo() *sdkws.UserInfo {
	if x != nil {
		return x.CallerInfo
	}
	return nil
}

var File_call_call_proto protoreflect.FileDescriptor

const file_call_call_proto_rawDesc = "" +
	"\n" +
	"\x0fcall/call.proto\x12\vopenim.call\x1a\x11sdkws/sdkws.proto\x1a%livekit_meeting/livekit_meeting.proto\"\x90\x02\n" +
	"\bCallInfo\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06roomID\x18\x06 \x01(\tR\x06roomID\x12\x1e\n" +
	"\n" +
	"createTime\x18\a \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"answerTime\x18\b \x01(\x03R\n" +
	"answerTime\x12\x18\n" +
	"\aendTime\x18\t \x01(\x03R\aendTime\"u\n" +
	"\rCreateCallReq\x12\"\n" +
	"\fcalleeUserID\x18\x01 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x02 \x01(\tR\bcallType\x12$\n" +
	"\ridempotentKey\x18\x03 \x01(\tR\ridempotentKey\"\x7f\n" +
	"\x0eCreateCallResp\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12=\n" +
	"\aliveKit\x18\x02 \x01(\v2#.openim.livekit_meeting.LiveKitInfoR\aliveKit\x12\x16\n" +
	"\x06roomID\x18\x03 \x01(\tR\x06roomID\"J\n" +
	"\x18RespondCallInvitationReq\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"Z\n" +
	"\x19RespondCallInvitationResp\x12=\n" +
	"\aliveKit\x18\x01 \x01(\v2#.openim.livekit_meeting.LiveKitInfoR\aliveKit\"1\n" +
	"\x17CancelCallInvitationReq\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\"\x1a\n" +
	"\x18CancelCallInvitationResp\"$\n" +
	"\n" +
	"EndCallReq\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\"\r\n" +
	"\vEndCallResp\")\n" +
	"\x0fGetCallTokenReq\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\"i\n" +
	"\x10GetCallTokenResp\x12=\n" +
	"\aliveKit\x18\x01 \x01(\v2#.openim.livekit_meeting.LiveKitInfoR\aliveKit\x12\x16\n" +
	"\x06roomID\x18\x02 \x01(\tR\x06roomID\" \n" +
	"\x1eGetMyPendingCallInvitationsReq\"X\n" +
	"\x1fGetMyPendingCallInvitationsResp\x125\n" +
	"\x05calls\x18\x01 \x03(\v2\x1f.openim.call.CallInvitationTipsR\x05calls\"\x80\x02\n" +
	"\x12CallInvitationTips\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x12\x16\n" +
	"\x06roomID\x18\x05 \x01(\tR\x06roomID\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\x126\n" +
	"\n" +
	"callerInfo\x18\a \x01(\v2\x16.openim.sdkws.UserInfoR\n" +
	"callerInfo\"\xe3\x01\n" +
	"\x11CallRespondedTips\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x12\x1a\n" +
	"\baccepted\x18\x05 \x01(\bR\baccepted\x126\n" +
	"\n" +
	"calleeInfo\x18\x06 \x01(\v2\x16.openim.sdkws.UserInfoR\n" +
	"calleeInfo\"\xc7\x01\n" +
	"\x11CallCancelledTips\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x126\n" +
	"\n" +
	"callerInfo\x18\x05 \x01(\v2\x16.openim.sdkws.UserInfoR\n" +
	"callerInfo\"\xa7\x01\n" +
	"\rCallEndedTips\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\"\xc5\x01\n" +
	"\x0fCallTimeoutTips\x12\x16\n" +
	"\x06callID\x18\x01 \x01(\tR\x06callID\x12\"\n" +
	"\fcallerUserID\x18\x02 \x01(\tR\fcallerUserID\x12\"\n" +
	"\fcalleeUserID\x18\x03 \x01(\tR\fcalleeUserID\x12\x1a\n" +
	"\bcallType\x18\x04 \x01(\tR\bcallType\x126\n" +
	"\n" +
	"callerInfo\x18\x05 \x01(\v2\x16.openim.sdkws.UserInfoR\n" +
	"callerInfo2\xa6\x04\n" +
	"\vCallService\x12E\n" +
	"\n" +
	"CreateCall\x12\x1a.openim.call.CreateCallReq\x1a\x1b.openim.call.CreateCallResp\x12f\n" +
	"\x15RespondCallInvitation\x12%.openim.call.RespondCallInvitationReq\x1a&.openim.call.RespondCallInvitationResp\x12c\n" +
	"\x14CancelCallInvitation\x12$.openim.call.CancelCallInvitationReq\x1a%.openim.call.CancelCallInvitationResp\x12<\n" +
	"\aEndCall\x12\x17.openim.call.EndCallReq\x1a\x18.openim.call.EndCallResp\x12K\n" +
	"\fGetCallToken\x12\x1c.openim.call.GetCallTokenReq\x1a\x1d.openim.call.GetCallTokenResp\x12x\n" +
	"\x1bGetMyPendingCallInvitations\x12+.openim.call.GetMyPendingCallInvitationsReq\x1a,.openim.call.GetMyPendingCallInvitationsRespB$Z\"github.com/openimsdk/protocol/callb\x06proto3"

var (
	file_call_call_proto_rawDescOnce sync.Once
	file_call_call_proto_rawDescData []byte
)

func file_call_call_proto_rawDescGZIP() []byte {
	file_call_call_proto_rawDescOnce.Do(func() {
		file_call_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_call_call_proto_rawDesc), len(file_call_call_proto_rawDesc)))
	})
	return file_call_call_proto_rawDescData
}

var file_call_call_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_call_call_proto_goTypes = []any{
	(*CallInfo)(nil),                        // 0: openim.call.CallInfo
	(*CreateCallReq)(nil),                   // 1: openim.call.CreateCallReq
	(*CreateCallResp)(nil),                  // 2: openim.call.CreateCallResp
	(*RespondCallInvitationReq)(nil),        // 3: openim.call.RespondCallInvitationReq
	(*RespondCallInvitationResp)(nil),       // 4: openim.call.RespondCallInvitationResp
	(*CancelCallInvitationReq)(nil),         // 5: openim.call.CancelCallInvitationReq
	(*CancelCallInvitationResp)(nil),        // 6: openim.call.CancelCallInvitationResp
	(*EndCallReq)(nil),                      // 7: openim.call.EndCallReq
	(*EndCallResp)(nil),                     // 8: openim.call.EndCallResp
	(*GetCallTokenReq)(nil),                 // 9: openim.call.GetCallTokenReq
	(*GetCallTokenResp)(nil),                // 10: openim.call.GetCallTokenResp
	(*GetMyPendingCallInvitationsReq)(nil),  // 11: openim.call.GetMyPendingCallInvitationsReq
	(*GetMyPendingCallInvitationsResp)(nil), // 12: openim.call.GetMyPendingCallInvitationsResp
	(*CallInvitationTips)(nil),              // 13: openim.call.CallInvitationTips
	(*CallRespondedTips)(nil),               // 14: openim.call.CallRespondedTips
	(*CallCancelledTips)(nil),               // 15: openim.call.CallCancelledTips
	(*CallEndedTips)(nil),                   // 16: openim.call.CallEndedTips
	(*CallTimeoutTips)(nil),                 // 17: openim.call.CallTimeoutTips
	(*livekit_meeting.LiveKitInfo)(nil),     // 18: openim.livekit_meeting.LiveKitInfo
	(*sdkws.UserInfo)(nil),                  // 19: openim.sdkws.UserInfo
}
var file_call_call_proto_depIdxs = []int32{
	18, // 0: openim.call.CreateCallResp.liveKit:type_name -> openim.livekit_meeting.LiveKitInfo
	18, // 1: openim.call.RespondCallInvitationResp.liveKit:type_name -> openim.livekit_meeting.LiveKitInfo
	18, // 2: openim.call.GetCallTokenResp.liveKit:type_name -> openim.livekit_meeting.LiveKitInfo
	13, // 3: openim.call.GetMyPendingCallInvitationsResp.calls:type_name -> openim.call.CallInvitationTips
	19, // 4: openim.call.CallInvitationTips.callerInfo:type_name -> openim.sdkws.UserInfo
	19, // 5: openim.call.CallRespondedTips.calleeInfo:type_name -> openim.sdkws.UserInfo
	19, // 6: openim.call.CallCancelledTips.callerInfo:type_name -> openim.sdkws.UserInfo
	19, // 7: openim.call.CallTimeoutTips.callerInfo:type_name -> openim.sdkws.UserInfo
	1,  // 8: openim.call.CallService.CreateCall:input_type -> openim.call.CreateCallReq
	3,  // 9: openim.call.CallService.RespondCallInvitation:input_type -> openim.call.RespondCallInvitationReq
	5,  // 10: openim.call.CallService.CancelCallInvitation:input_type -> openim.call.CancelCallInvitationReq
	7,  // 11: openim.call.CallService.EndCall:input_type -> openim.call.EndCallReq
	9,  // 12: openim.call.CallService.GetCallToken:input_type -> openim.call.GetCallTokenReq
	11, // 13: openim.call.CallService.GetMyPendingCallInvitations:input_type -> openim.call.GetMyPendingCallInvitationsReq
	2,  // 14: openim.call.CallService.CreateCall:output_type -> openim.call.CreateCallResp
	4,  // 15: openim.call.CallService.RespondCallInvitation:output_type -> openim.call.RespondCallInvitationResp
	6,  // 16: openim.call.CallService.CancelCallInvitation:output_type -> openim.call.CancelCallInvitationResp
	8,  // 17: openim.call.CallService.EndCall:output_type -> openim.call.EndCallResp
	10, // 18: openim.call.CallService.GetCallToken:output_type -> openim.call.GetCallTokenResp
	12, // 19: openim.call.CallService.GetMyPendingCallInvitations:output_type -> openim.call.GetMyPendingCallInvitationsResp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_call_call_proto_init() }
func file_call_call_proto_init() {
	if File_call_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_call_call_proto_rawDesc), len(file_call_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_call_call_proto_goTypes,
		DependencyIndexes: file_call_call_proto_depIdxs,
		MessageInfos:      file_call_call_proto_msgTypes,
	}.Build()
	File_call_call_proto = out.File
	file_call_call_proto_goTypes = nil
	file_call_call_proto_depIdxs = nil
}
